== Forward

James Nayler was a prominent leader and gifted
minister in the early Society of Friends in England.
Though a farmer by trade, and a man of limited education,
his deep spiritual understanding, piercing discernment,
and powerful communication of the gospel caused multitudes to acknowledge
that he preached in the demonstration of the Spirit and power,
as one having authority, and not as the scribes.
Sadly, he is best known for a single (and much regretted) act
of folly committed in a time of weakness and temptation,
when, "`because of the abundance of revelation`" and the
unchecked flattery of a few imprudent admirers,
he accepted greater praise than is due to any man (as
the appendix to this volume relates in detail).

The complete works of James Nayler in four volumes are available today,
but the great majority of readers find his original writings quite unmanageable.
Beyond the difficulties presented by archaic words, spellings, and expressions,
Nayler wrote in what might be called a "`stream of consciousness`" style,
setting forth in long run-on sentences (with apparently little forethought
or organization) the thoughts and arguments that flowed into his mind.
To the eyes of a modern reader,
the writing style of the 1600`'s is often considered unnecessarily wordy and convoluted,
but Nayler`'s writings are particularly challenging in this respect.
In fact, when George Whitehead (an intimate friend and fellow-Quaker)
first published Nayler`'s complete works in 1716,
he made literally thousands of alterations to Nayler`'s original words and expressions,
not because of any difference in sentiment or doctrine,
but entirely with a view to greater clarity of communication.

With a similar motivation to that of George Whitehead,
and from a strong desire that the writings of this
pious and experienced Christian not be lost in history,
I have taken upon myself the task of carefully
modernizing some of Nayler`'s most notable works.
Modernizing is not a simple or straightforward task, and can easily be done poorly.
Attempts to modernize early Quaker documents
without a deep understanding of their context,
vocabulary, religious culture,
and particular testimonies have led to some very unsatisfactory results.
For this reason, I have approached the task with the greatest care and seriousness,
and hope that I am in measure qualified for the
work by a true intimacy with Friends`' literature,
having read and re-read many thousands of pages (in their
original format) for my own personal edification and enjoyment;
also by a heartfelt agreement with the spiritual views contained in them;
by a very real sense of loving esteem and respect for the original authors;
by an admittedly imperfect but sincere attempt to live by the
same light and grace to which the Quakers testified;
and by a measure of the fear of the Lord--believing that the Spirit of God
is the true source of much of what is presented in these writings.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
September, 2018
