== Chapter II. The Lamb`'s War / Against the Man of Sin

[.chapter-subtitle--blurb]
The end of it, the manner of it, and what He wars against; His weapons, His banner,
and His kingdom, and how all may know whether they be in it or not;
and whether the same Christ is in them that
"`is, was, and is to come,`" and their faithfulness or unfaithfulness to Him.

The Lord God Almighty, to whom belong all the kingdoms in heaven and earth,
does nothing therein except by His Son, the Lamb.
By Him He creates and governs; by Him He saves and condemns, judges and justifies,
makes peace and makes war.
Whatsoever He does, He is at the Father`'s right hand in all places,
who in Him has long endured the burden of iniquity and the oppression
of wickedness that has abounded for many generations.

And now His appearance in the Lamb is to make war with the god of this world,
and to plead with His subjects concerning their revolt from Him--
their Creator--who ordered their beginning and gave them a being.
For having broken the order that was in the beginning,
and given their obedience to the worldly spirit with his inventions,
they have now become so far one with that spirit
that they have defiled their souls and bodies,
blinded their eyes, stopped their ears,
and made the creature utterly unprofitable to God and
unfit to be a temple in which He can be worshipped.
They can no longer hear the voice or understand the
mind of the eternal Spirit (by which they were created),
but have become open enemies to every check and reproof
of the Spirit which was given to lead them to God.
This good Spirit does testify against their evil deeds,
but they are not afraid to speak against it as a thing not worth minding,
nor able to lead them in the way of truth.
Thus the creature has fallen from God`'s call and service,
and has become one with the god of this world,
to serve and obey him in ways that insult the Spirit of grace,
now using the creation against the Creator.
Thus, it is against this evil seed,
and against its whole work brought forth in that nature,
that the Lamb makes war to take vengeance upon His enemies.

[.offset]
_The end of His war is:_ To judge this deceiver openly before all the creation,
showing that his ways, fashions,
and customs are not how God ordered man to live in the beginning.
So He seeks to bind him and to redeem man out of his captivity,
all who believe in the Lamb, and are weary of their service and bondage to His enemy,
and will but come forth and give their names and hearts to join with Him,
and bear His image and testimony openly before all men.
These, who willingly follow Him in the way wherein the
Father has given victory over the enemy`'s power,
are made new and redeemed to God, so that God alone may rule in His own work.
But the rest who will not believe and follow Him, and bear His image,
will be condemned with the destroyer into everlasting destruction.

[.offset]
_The manner of His war is:_ First,
in order that He may be just (who is to judge all men and spirits),
He gives His light into their hearts, both men and women,
whereby He lets all see (whoever will mind it) what He is displeased with,
what is with Him,
and what is against Him, what He owns, and what He disowns.
By this light all may know what is determined for destruction, and so come out of it,
lest they be destroyed with it;
for it is His desire to save and receive all that are not willfully
disobedient and hardened in the pleasures of this world against Him.
Yes, He will receive all who are deceived but are willing to be undeceived,
all who are taken captive but are willing to be set free,
all who are in darkness but are willing to come to light; in a word,
all who love righteousness more than the pleasures of sin.
He has no desire to destroy them, nor to see them ignorantly fight against Him.
Instead, His desire is to receive them unto Himself,
that they may be one with Him against that power which has misled and deceived them.
And as many as turn at His reproof, He does indeed receive,
and gives them power in spirit and life to be as He is, according to their measure.
But all must abide in watching and warring against that which has had them,
and which has the rest of the creation in bondage,
that He may restore all things to their former liberty.

[.offset]
_What they are to war against:_ They must war against whatever is not of God,
whatever the eye (which loves the world) lusts after,
whatever the flesh takes delight in,
and whatever stands as a respecter of persons (as the
Scripture says)--the lust of the eye,
the lust of the flesh, the pride of life.
These are not of God,
and whatever the god of this world has begotten
in men`'s hearts to practice or contend for--yes,
whatever God did not place there--all this the Lamb and His followers must war against,
and they must be at enmity with it both in themselves and wherever they see it.
For the kingdom is known in the work of God alone, and all other works He will destroy.

So their war is not against the creature,
for they wrestle not with the flesh and blood which God has made,
but with spiritual wickedness, exalted in the hearts of men and women,
where God alone should be.
For by embracing and contending for the works of the devil,
they have become enemies to God, and their souls are destroyed.
Thus the Lamb`'s war is against the whole work
and design of the god of this world--his laws,
his customs, his fashions, his inventions,
and all which seeks to add to or take from the work of God as it was in the beginning.
All of this is at enmity with the Lamb and His followers,
who have entered into the covenant which was in the beginning,
and it is therefore no wonder that they are
hated by the god of this world and his subjects.
For the Lamb comes to spoil him of all that he has,
and to destroy the whole body of sin (the foundation and strength of his kingdom),
and to take the government to Himself, that God may rule wholly in the hearts of men,
and men may wholly live in the work of God.

[.offset]
_What their weapons are:_ As they war not against men`'s bodies,
so their weapons are not carnal, nor hurtful to any of the creation;
for the Lamb comes not to destroy men`'s lives, nor the work of God.
But with His appearance in His subjects,
He puts spiritual weapons into their hearts and hands.
Thus their armor is the light, their sword is the Spirit of the Father and the Son,
their shield is faith and patience,
and their paths are prepared with the gospel of peace
and good will towards all the creation of God.
Their breastplate is righteousness and holiness to God,
their minds are girded with godliness, they are covered with salvation,
and they are taught by truth.
And thus the Lamb in them, and they in Him,
go out in judgment and righteousness to make war with His enemies,
conquering and to conquer.
They war not as the prince of this world does through his subjects,
with whips and prisons, tortures and torments on the bodies of creatures,
to kill and destroy men`'s lives;
but the followers of the Lamb go forth in the power of the Spirit with the Word of truth,
to pass judgment upon the head of the serpent who deceives and bewitches the world.
And through these faithful ones, the Lamb both covers His own with love,
and kindles coals of fire upon the heads of His enemies.

For with the "`spirit of judgment and the spirit of burning`"^
footnote:[Isaiah 4:4]
the Lord will plead with His enemies;
and having kindled the fire and awakened the creature,
and broken their peace and rest in sin,
He waits in patience to recover the creature and to slay the enmity.
And though the evil spirit that rules in the
creature casts up all manner of rage and envy,
the Lamb continues to pity, offering love for hatred,
and wrestling with God against the enmity--with all intercession, patience,
long-suffering, and faithfulness, in truth and unfeigned love,
and with all the fruits of the Spirit, so that, by any means,
He may overcome evil with good.
And by His light,
He seeks to open that eye in the creature which the god of this world has blinded,
in order that men may learn to abhor what God abhors,
and see the fruits of death that they have brought forth.
In this way all may see and be convinced that the light is no deceiver,
but has the life and power of innocence and holiness, wherever it rules.

Truly,
the Lamb`'s inward preaching has power to open the eyes of all that
are not willfully blind because they love the deeds of darkness;
and such as these are (by the light) left without excuse forever.
But through His subjects the Lamb many times wrestles and preaches to the spirits in prison,
with great long-suffering towards the world, towards nations,
and towards particular persons, before He gives them up and numbers them for destruction.
Yes, sometimes He pursues them until their rage against Him,
and the cruelty they exercise upon His members, becomes so great that there is no remedy,
as it was in the days of old:

[quote.scripture]
____
And the LORD God of their fathers sent warnings to them by His messengers,
rising up early and sending them,
because He had compassion on His people and on His dwelling place.
But they mocked the messengers of God, despised His words, and scoffed at His prophets,
until the wrath of the LORD arose against His people,
till there was no remedy.footnote:[2 Chronicles 36:15-16]
____

Now, these fruits are the banner which the Lamb holds forth
to all the world in those in whom He reigns:
As they come to obey Him, He covers them with love, gentleness, faith, patience,
and purity, grace and virtue, temperance and self-denial, meekness and innocency,
and all in white.
These are they that truly follow the One who is in them,
who "`walk themselves even as He walked`"^
footnote:[1 John 2:6]
in all things conformable to God, with boldness and zeal,
knowing the Lamb to be their leader,
and together with Him testifying against the world that their deeds are evil.
And these are covered with His righteousness against
all the storms and tempests they will surely meet with,
together with all who have borne His testimony;
for the Lamb has borne one testimony from the beginning for the convincing of the world.
Thus, all who are willing to believe and to love holiness will see where it is to be found,
and will come out to Him and be saved,
that the whole world does not become as Sodom in the day of wrath.
For the day of wrath comes upon all people and nations
after Christ has thus appeared and been rejected.

=== What His Kingdom Is

The power, the glory,
and the compass of the kingdom of God are not comprehended with mortal understanding,
for it was before all beginnings, and endures forever,
and orders and limits all spirits in heaven and earth.
It rules in the rulers of the earth, and in all heavenly places,
though often men know it not till they have felt
His reproof for their rebellion against it.
Indeed, He has dominion among the heathen,
and His hand is in the counsels of the kings of the earth,
and there is no place where He is not, who descends below all depths,
and ascends far above all heavens, that He may fill all things.

But His kingdom in this world,
in which He chiefly delights to walk and make Himself known,
is in the hearts of such as have believed in Him,
and have answered His call out of the world; whose hearts He has purified,
and whose bodies He has washed in their obedience,
making them fit temples in which the Father is worshipped.
In these He rejoices and takes delight,
and His kingdom in such is righteousness and peace.
In love, power, and purity,
He leads them by the gentle movings of His Spirit out of all their
own ways and wills (in which they would defile themselves),
and guides them into the will of the Father, by which they become more clean and holy.
He lets them know the depths of His covenant, and how far they may go and be safe.
He gives them His laws and statutes which are
contrary in every way to the god of this world,
that they may be seen to be His before all His enemies.
If they keep His counsel they are safe; but if they refuse,
He lets them know the correction of the Father.
His presence is great joy to all who have a willing mind;
but with the crooked He shows Himself astute.
The kisses of His lips are life eternal, but who may abide His wrath?
The secrets of the Father are with Him, and He makes all His subjects wise.
He makes them all of one heart--one with Himself, and of the same mind.
His government is wholly pure, and no unclean thing can abide His judgments.
As any truly come into His kingdom they are known,
and their change is to be seen by all men.
He keeps them low in mind, and begets a meek spirit in them.
And with His power He leads them forth against all the enmity of the evil one,
teaching the one who abides in His kingdom to be content in all circumstances.

Now is the time when many false Christs must
appear and be made manifest by the true Christ,
with all their false prophets, false ways, false worships, and false worshippers, who,
though they are at war with one another, do not know the Lamb`'s war.
So then, seeing He has appeared who is from everlasting and does not change,
here is an everlasting trial for you all,
to see whether you profess Him from the letter or from the light.
Come now and see whether Christ is in you!
Measure your life, and weigh your profession with that light which cannot deceive you,
which has stood and will stand forever.

In all truth, before God and before your own souls,
prove your work while there is time, lest you and your work perish together.
First, see if your Christ is the same that was from everlasting to everlasting,
or if He changes according to the times: in times of life and death, peace and wars,
in reigning and in suffering, etc.
And if indeed you have found the true Christ,
then prove your faithfulness to Him in all things.
Does He whom you obey as your leader lead you out to war against this world,
and all the pride and glory, fashions and customs, loves and pleasures,
and whatever else is not of God?
Does He lead you to give up your lives unto death,
rather than knowingly yield your obedience to sin?
Does He justify any life in you now besides what He justified in the prophets, apostles,
and saints of old?
Does He give His subjects liberty now to bow to the god of this world and his ways
in things which He has forbidden in the saints of old (for the denying of which,
many both then and now have suffered)?
Is He at peace in you while you live in fleshly pleasures or
find fellowship with the unclean spirits that are in the world?
Does He not lead out of the world, and to strive against it in watchings, fastings,
prayers, and strong cries to the Father,
that you and others may be kept and delivered from the bondage and pollutions of it?
Is this the kingdom you have found in yourselves?

And does He give out the same spiritual laws against
all the ways and customs of the man of sin in you,
as He has done in His subjects in all ages?
Does He beget in your hearts a new nature that is contrary to the world`'s nature,
motions, and delights in all things,
whereby He works out the old nature which inclines to
the world and can be at peace with it?
Is your peace now wholly in Him, and is that which crucifies the world to you,
and you to it, your true joy and delight?
Has He called you out of this world to bear His name before its powers,
putting His testimony into your hearts,
and the same weapons into your hands that were used by
the saints of old against the powers of darkness,
whereby you find power to overcome evil with good?
Indeed, there are many other fruits which He has always brought forth in His chosen ones,
whereby they were known to be in Him, and He in them,
for which reason the world has hated them.
And by all of these you may clearly know if He is the
same in you today as He was yesterday in His people,
and will be forever.
For the Lamb does not change, nor conform to the world or the will of any creature,
but rather changes all His followers till they become like Him in all things;
for they must bear His name and image before all men and spirits.

Does it not greatly concern you to try your state,
seeing how all must soon give an account for their lives and service?
Or have you gone out like the beast of the field,
regarding nothing but your bellies and your pleasure?
Do you spend your time and strength in watching and praying to
the Father of spirits for yourselves and the people of God,
that they may be kept in the time of temptation and the assaults of
the evil one (who seeks his advantage on weaker brethren)?
Do you pray for your enemies, that they may be delivered from under his power,
who are captivated by him to do his will, to fulfill his lusts and envy,
and satisfy his wrath upon the innocent?
And do you deny yourselves of pleasures, profits, ease and liberty,
that you may hold forth a chaste conduct in the power and life of gentleness, meekness,
faithfulness and truth?
Is your conscience void of offense towards God and all men so
that thereby you may shine forth in righteousness,
and convince the enemies whom you pray for,
thus following the One who laid down His life for His enemies?
Is this your war, and are these your weapons?
Is this your calling, and are you faithful to Him that has called you,
so that you can by no means bow to the god of this world, nor his ways,
even to save your lives or credit or estates in the world?
And yet can you serve the lowest creature in the way of God,
though it mean the loss of all?

I beseech you, be faithful to your own souls and consider:
Do you find something in you that calls or moves in this way,
or reproves you for the contrary?
If there is, are you one who quenches this Spirit, closes your eyes,
and denies the Lamb`'s call against your own life?
And if there is not, is not your profession of Christ a lie?
Are you not dead members, cut off from Him, and without God in the world?
O that you would prove yourselves!
For there are many deceitful workers in this day of His appearance,
who do the work of the Lord negligently and deceitfully,
doing their own work instead of His.
And there are many who are called, and who abide for a while,
but in the time of hardship prove deceitful,
and return to serve and take pleasure in the world.
Others are called and convinced, but come only halfway out of the world,
as far as they can without loss or shame,
but keep their covenant with it in whatever makes most for their gain, credit,
or earthly advantage.
Still others have answered their call,
and been faithful in the covenant of the Lamb against
the prince of this world so far as they have seen,
but not staying on the watch against the enemy,
and not keeping low in the fear and zealous in the light,
have allowed their simplicity to be deceived,
and are led back into the old beggarly rudiments of the world again,
taking for their perfection and growth what they once had vomited up.
These expect great things in their work, but they are blinder than the rest,
and more to be pitied, because their simplicity is deceived and lost.
And there are many other grounds that do not bring forth fruit unto perfection,
who are not found faithful to Him that has called them,
and so it is now true that "`many are called, but few are chosen`"^
footnote:[Matthew 20:16; 22:14]
and faithful.
Many are ashamed at the Lamb`'s appearance,
for it is so low and weak and poor and contemptible,
and others are afraid when they see so great a power against Him.
And many are at work in their imaginations seeking to understand the kingdom,
and get power over sin, and find peace of conscience,
but few will deny all to be led by the Lamb in a way they know not,
to bear His testimony and His mark against the world, and to suffer for it with Him.

Now deceit has taught you to say (and maybe you think it true),
'`God forbid but that I should suffer with Christ until death!`'
But come to the trial in deed and truth!
Does He not suffer in the heart of man under all the pride and pleasures of the flesh,
and by all manner of excess and customs and
fashions which are not of God but of the world?
Are not all things against Him which are not of Him and of the Father?
Are not the lust of the eye, the lust of the flesh,
and the pride of life His oppressors in man?
And you who live in these things,
and in the world`'s fashions (and even contend for them),
are you truly suffering with Him because of them, and warring with Him against them?
For then you would be weary of them, and cease to practice and plead for them against Him.
But this you will find to be true in the end:
you cannot both suffer with Him and serve His enemies.

Oh, all you hearers of sermons of every sort,
how long will it be before you hearken to what the Lord says in your own souls,
who is no respecter of persons?
For He rejects all who bear not the image of His Son in well-doing,
though they sacrifice with Cain, or pray in tears with Esau.
Oh that with the light of Christ in your own hearts you would see how
the world`'s lusts have spoiled your souls of the heavenly image,
and the spirit of the world has captivated your minds to itself and its likeness;
and how you lie dead in sin, covered with earth, and daubed over with the words of men.
Oh that you would awake before wrath awakes you, and put on the armor of God,
not relying any longer on men who beat the air to fight your battles,
against an enemy who has already gotten into your hearts.
But, as soldiers of Christ,
may you all come to use spiritual weapons against all
spiritual wickedness that is exalted in the temple of God,
for this fills the heart with wicked and worldly encumbrances
so that you can neither see nor serve the Lord.

With these spiritual weapons,
every thought is to be taken captive to the obedience of Christ.
This is the true warfare,
and it is "`mighty through God to the casting down of every
stronghold`" of the man of sin in you--"`being ready to punish
all disobedience when your obedience is fulfilled;`"^
footnote:[2 Corinthians 10:4-6]
for whatever will not be led by the Spirit of God is for condemnation.
These weapons alone are effectual toward cleansing the heart
from all that rises up against the life and knowledge of God,
for they make way for His appearance by the power of Christ--
His light and life--which no man`'s words have power to do.
And blessed are they who feel and find this treasure working in their earthen vessel,
for such shall approve their own work to God, and have praise from Him and not from men.
Thus you will come to see what others have said in Scripture
concerning "`the Lamb of God who takes away the sins of the world,`"^
footnote:[John 1:29]
for you will savingly feel the power of His cross, His death and resurrection,
and the everlasting purity of His life,
to which the eternal love of the Father flows freely.

Called, chosen, and faithful are the servants and subjects of Christ`'s kingdom,
in whom (at this day) He wages war against the prince of this world,
the beast and false prophet,
and all that serve under Satan`'s dominion and obey the laws he has set up.

Now, you that cry,
"`The kingdoms of the world have become the kingdoms of the Lord and of His Christ;`"^
footnote:[Revelation 11:15]
see that this be true in you, and that you do not lie to yourselves.
You must know the Lamb`'s war before you can witness His kingdom,
and "`those who are with Him are called, chosen, and faithful.`"^
footnote:[Revelation 17:14]
He that preaches the kingdom of Christ in words, without knowing the victory,
is the thief that goes before Christ.
So take heed that your own words do not condemn you;
but mind your calling and how you have answered it,
and whether you have been faithful in the war unto which you have been called.
For Christ has a war with His enemies,
and He calls His subjects to serve Him therein
against all the powers of darkness in this world.
He will overturn all things of this old world--all of its ways and fashions--
and will make all things new which the god of this world has polluted.
For in these things the children of the devil have corrupted themselves,
and served the devourer by following their lusts.
And it is against such things that the Lamb makes war in whomsoever He appears.
Yes, He calls all men to join to Himself, in heart and mind and with all of their might.
And for this end He has lit His candle in their hearts,
that they may find out every secret evil that the man of sin has there treasured up,
even the thoughts and intents of the heart.
There He will cast out the strong man with all his stuff,
and subject the creature wholly to Himself, that He may form a new man, a new heart,
new thoughts, and a new obedience, in a new way,
in all things therein to reign--and this is the kingdom of God.

Now many are called to this war, but few are chosen and faithful.
They that are faithful in their calling, these He chooses, and in them He reigns,
and with them He makes war against His enemies on every side,
under whatsoever banner they appear.
The sword of His Spirit He has put into their hand, and His Word is in their mouth,
and with these they make war with all the world,
even all that will not be subject to Him; and indeed, the world is at war with them.
And he that is faithful will make no peace or agreement,
neither will he bow or yield till there be a subjection to Christ.
These are faithful to Him that has called them.

So you that are great in words, prove yourselves,
whether you are truly in His kingdom and among His subjects!
For if you are, you are at work with Him in this His day,
in which He is coming "`in thousands of His saints, to take vengeance`"^
footnote:[Jude 1:14-15, Literal Translation]
into His hands, and inflict it upon His enemies.
But you who are asleep and at ease in the flesh,
at peace in the world`'s ways and fashions,
which are invented and maintained by the man of sin--you are not of His kingdom.

But you will say, "`God is love, and we are commanded to love all,
and seek peace with all, etc.`"
I say, is God`'s love in you different than it has ever been in Christ and all His saints,
whom the world ever hated, but whom God loved,
and in whom He testified against the world even unto bonds, persecution, and death?
Were not these in God`'s love?
Did they not keep His commandments?
And will you take their words in your mouths and condemn their lives by your practices?

The Lamb`'s war is not against the creation, for then His weapons would be carnal,
like the weapons of the worldly spirits.
But "`we wrestle not with flesh and blood,`"^
footnote:[Ephesians 6:12]
nor against the creation of God.
No, the creation we love;
but we fight against the spiritual powers of wickedness which war against God
_in the creation_ and take it captive into lusts which war against the soul,
so that the creature may be delivered into the liberty prepared for the sons of God.
And this war is not contrary to love, nor contrary to everlasting peace,
for without it there could be no true love or lasting peace.
Indeed, it is our love to God and man that constrains us to be faithful in this war.

But the love of God is not to that seed of bondage,
nor did He ever command you to seek the peace of that seed;
"`for the friendship with the world is enmity with God,`"^
footnote:[James 4:4]
as the Scripture says.
And had you not fallen into self-love (which is utterly blind as to the love of God),
you would see a great difference between the creature and the seed
which keeps the creature in bondage and out of the love of God.
Can you love that evil seed and not hate the creature, and God also?
All who know the Lamb`'s battles, who are in the true love of God, know these things well.

For does not the spirit of pride, gluttony, drunkenness, pleasures,
envy and strife, keep the creature (who you should love,
according to God`'s command) in bondage?
Does not the creature groan to be delivered from the vanity,
customs and fashions of this generation?
And is not the whole time of man taken up in the service of lusts and inventions
which the man of sin has conceived--inventions in foods and drinks,
in apparel, in worship, in sports and pleasures,
etc.? Is not the whole of creation captivated under this spirit of harlotry,
so that a man`'s whole life is often spent in vain?
Alas, men and women come into the world and depart out of it again as
though they were made for no other end but vanity and selfishness;
scarce one in ten thousand knows any call from God to serve Him,
or has an ear to hear that voice.
And if any do hear and obey, the world concludes them deceived,
and is ready to devour them because they testify
against the evils which destroy men`'s souls,
and make void man`'s service to his creator and devour the creation.

And can you love this spirit, bow and conform to it,
or allow it to reign in yourselves or your brethren,
and still pretend to seek love and peace, and to obey God`'s commands,
boasting in lofty words about Christ`'s kingdom?
And do you count it a low and foolish thing when men faithfully and
zealously bear their testimony for God against these evils?
Will not God eventually find you out,
and expose your deceit and unfaithfulness in your generation?
Will He not break your peace and annul the covenant you are making
with the world to settle yourselves in ease and pleasure?
Will He not bring you out with true judgment,
wherein it will be seen of what nature your love is, and whose kingdom you are in,
and who it is that you love and serve?

The Day has dawned, and the Sun has risen for many, and it shall not set,
nor cease its course,
until He has rightly divided between the precious seed
and the children of harlotry and deceit.
And now the holy seed is called forth to appear with its banner against the man of sin,
and with "`the sword of His mouth He makes war,`"^
footnote:[Revelation 2:16]
and "`with the spirit of judgment and the spirit of burning`"^
footnote:[Isaiah 4:4]
He consumes all that is filthy and unclean.
And all that are faithful have their armor on,
ready day and night to follow the Lamb as He moves,
counting nothing too hard if they may preach reconciliation between God and
the creature to those who have fallen to the prince of the world,
and been led captive according to his will.
And this is love indeed to lay down all for such as are yet enemies.

Oh, perilous times have come!
Now is the earth and the air corrupted and filled with violence and deceit,
and ungodliness abounds everywhere.
Satan is loosed and has gone forth to deceive;
multitudes of spirits are sent abroad and have power
given them to enter all who dwell in the earth,
who inhabit dark places, who love not the light.
Woe to the world; woe to all who have treasured up wickedness in themselves!
For Satan will seek out his own in them,
and his vessels will be filled--filled with wrath, filled with pride, filled with lust,
covetousness, and all manner of unrighteousness.
Every bottle must be filled, that the Potter may dash them one against another.
Woe to the drunken nations whose uncleanness is in their streets; yes,
whose streets are filled with pride, filled with oppression and deceit, lying,
swearing and cursed speaking.
Their filth is vomited out openly and yet they are not ashamed.
Vanity and folly have become their glory, wickedness shines boldly,
not in a corner but in the broad places of the streets.

Alas, there is no safety for any who look outward,
for sin lies at the door ready to enter!
And now the watchmen are blind (having become enemies to the light),
so that the house is easily filled with evil spirits.
Legions of devils may enter and inhabit the darkness--proud spirits, lying spirits,
flattering spirits, deceitful spirits of all sorts, which, being let in,
work in the vessel according to their several natures.
Yes, they work the works of their father the devil,
holding forth his image to all that look outward,
tempting all in order to enlarge his kingdom.
For when the lust of man looks outward,
then pride calls and holds forth an object to the eye, which being let in,
conceives and grows until it can bring forth its own increase,
and become a tempter to others.
Vanity calls out from the devil`'s treasury to all that pass by!
Spiritual harlotry cries aloud in the streets to
entice the simple and defile the virgins,
seeking to pollute the chaste spirit and corrupt the mind from God.

It is only by watching in the light with diligence, faithfulness and patience,
that the enemy is kept out, and his seed is killed within.
But while the root of pride and lust remains within,
it is fed by fetching in more of its own kind from without.
But the faithful watch allows him no passage--
neither in nor out--and so his supply is cut off,
and the seed of the evildoer is kept in captivity,
and the devil cannot come to relieve his own.
For, notwithstanding "`a man`'s enemies are those in his own house`"^
footnote:[Matthew 10:36]
(which is the case with all until they be truly dead and buried),
yet a faithful watch in the light will keep the soul from being deceived.
And though the tempter will seek to draw out the mind with all
his wiles and subtlety that he may come into his own,
yet into the light he cannot enter.
So he that dwells in the light dwells in God and has immortality for his defense.
Such as these hold fast to the Head, and feel His power of meekness, truth, peace, love,
and patience; and learning to stay their heart and mind on Him,
they are not tempted to depart.
For Christ is given by the Father to be head to the "`church which is in God,`"^
footnote:[1 Thessalonians 1:1; 2 Thessalonians 1:1]
which dwells in the light,
and He is over all principalities and powers and all spiritual wickedness.
This is the Savior, and is that name and nature to which
"`every knee must bow, and every tongue confess,`"^
footnote:[Romans 14:11]
and all who put Him on in truth and righteousness put on immortality,
eternal life, and freedom.
