[short="How Sin is Strengthened"]
== Chapter III. How Sin is Strengthened / &amp; How it is Overcome

That sin is in the world, and that all have thereby become children of wrath,
is generally believed and confessed by all;
but how sin is strengthened in men and women against God and against their own souls,
or how it is overcome, few rightly understand or have a desire to know.
Yet for the sakes of those who do,
I here declare something of what I have received from
Him who is faithful and true in all His testimony.

=== How Sin is Strengthened

This I have found: that even as sin got its root at first through lust,
so to this day it gains its strength by desires going forth to
lust after something--whether it be spiritual or carnal,
or anything above, before or besides what the eternal Spirit communicates to man,
or begets in him.
For the inward eye of mankind is blinded by the god of this world,
which eye should look unto God for all things;
and there is another eye open (the eye of unbelief), which looks unto visible things,
and gives occasion for lust to bring forth affections and desires
after something which the Spirit of God does not lead into.
Then all the power and wisdom that is in man is
set to work for the obtaining of his desire,
and this becomes sin both in the desires and actions; and the more it is followed,
the stronger it becomes.

Now, whatever is hereby obtained becomes a treasure of wickedness,
laid up within, in the dwelling place of the wicked one, whereby lust is increased,
and the Seed of God^
footnote:[Sown into the heart of man.]
is burdened and buried.
Man thereby becomes daily less sensible of the will of God,
and the movings of that pure Spirit which should keep the soul alive to the Creator,
and draw the mind wholly up to the Father to
wait upon Him alone for the supply of all things,
both for soul and body.
But every desire that springs from this root of evil, being allowed to go forth,
defiles the man, and brings in that which oppresses the Just One,
until by continuance man grows into the nature of the enmity,
and the imaginations of the heart become wholly evil,
and that Witness in him which should give the knowledge
of God and the knowledge of sin is buried.
In this way man becomes callous and "`past feeling,`"^
footnote:[Ephesians 4:19]
utterly dead in sins and trespasses,
which become by custom as natural to commit as for the ox to drink water.

Yes, it is with greediness that man in this condition hunts after his own destruction,
having dammed up the way of Life in himself by so often transgressing it.
Indeed, he has become degenerate from the nature of God, having received in,
and willingly joined to, that nature of Satan, which, like leaven,
works all who receive it and yield to it into its own nature.
And as they grow therein, the fruits of the same root and nature spring up,
which man brings forth with delight,
being always furnished with subtle ways to color and justify his wicked deeds.
Yes, being in covenant and agreement with sin (some in one thing and some in another)
everyone pleads for the allowance of that sin which most suits their present lusts,
pride, profit, pleasure, credit or esteem in the world, or some other selfish end.
With the world they take counsel (and not with
the Spirit of the Lord) to know what is sin,
and what is not sin,
but none will believe that they can be set free from all sin
by Him who testifies against all sin by His own Spirit.
So it is that "`the man of sin`"^
footnote:[2 Thessalonians 2:3]
gains his kingdom by consent, for man,
being willing to keep covenant with him in one evil, becomes guilty of all.

=== How Sin is Overcome

Now the way to overcome these things,
and overcome the one who has his power therein, is by faith in Christ Jesus--the Light,
and Life, and Way to the Father.
For without believing there can be no victory; but in the faithful following of Him,
the patient bearing His cross and enduring His sufferings, the enmity comes to be slain,
captivity is led captive,
and man is set at liberty in the holy Seed to serve the Father in Spirit and life again.

First, Christ (being the Light of the world) must be believed,
for He comes to manifest and reprove the deeds of darkness,
and to open true judgment and give discernment.
His light makes a separation between the works of God and the
works of the devil in the mind and spirit of the creature,
letting man see what spirit exercises his mind and affections, along with the moving,
working, and fruit of each spirit.
Without this light, none can rightly know what must be destroyed, and what must be saved;
what we must join to, and what we must war against;
for by this light alone man comes to the knowledge of sin in himself, in its ground,
root, and all of its motions.
Though the written letter, or some other external means,
may show what sin is by the clear fruits that are brought forth,
yet only the Spirit within can discover spiritual
wickedness in its first motion and rise,
which is the only place to kill it before it becomes sin in the creature.
This light must be believed and diligently minded all along,
for such is the subtlety of the enemy,
having gotten power over the will and the senses of man,
that he will set them to war against the creature to destroy the work of God in the soul.
This cannot be avoided any other way than by minding the light of Christ,
in order to make a separation between that which is to be cleansed,
and that which is to be destroyed.
No matter how much a man might seek after this, it cannot be done without the Spirit,
for it is a spiritual work.

And here is the cause why many are kept at hard labor all their time,
and never come clear out of sin and uncleanness--because they do not
believe in that which has the power to separate and lead out of evil,
but instead set to work in the dark, without that eye which sees a clear separation.
So it is that some destroy themselves in their attempts to destroy sin, and,
not minding the light of the Savior,
are led by the destroyer to fight against that part which Christ comes to
save (even while he that comes to destroy lies hidden in the dark).
But he that believes in the Light which manifests all things, reproves all things,
and judges all things, will (with the true eye) see what to war against,
and what to join with all along in the work.
For Christ alone is the covenant of light, and He is given for a leader.
And whosoever believes and follows shall not err in judgment or practice;
but unbelief in this Light is the cause why there are so many blind guides,
and why so many people die in their sins.

Thus Christ is the Way of God,
and is to be believed in as He manifests the works of the devil and
distinguishes them from the works of God--condemning the one in the flesh,
and justifying the other in the Spirit.
And as He manifests every spirit together with its working, motion, and end,
and its ground and increase, showing from where they come and to where they return,
hereby the creature may know who it is that exercises his mind and members,
and to what spirit he yields himself in his obedience and service.
In this way man may come to know the use and end of all his works, what to choose,
what to refuse, what to justify, and what to condemn in its first motion,
before it is brought forth or formed.
In this way judgment may be kept continually upon the head of transgression,
and liberty proclaimed to the Just One within, to reign without obstruction.

It is for lack of faith, and not coming to feel Christ in this way,
that so many perish in sin,
even while seeming to strive against sin--because they do not
believe that the light is sufficient to save from sin.
For the light manifests sin while still in the ground, before it has sprouted,
and condemns it in its first motion.
And if man would but join with Christ, in faith and diligence,
to condemn sin in the ground, in its first temptation and motion,
it would wither and die, and not long be able to live or prevail.
And if, for a time, it should continue to live in the members,
yet this would not be unto condemnation;
for I have seen a great difference between sin condemned in the creature (though
not yet wholly dead) and sin lived in and pleaded for.
For if your life and judgment is in that Light which condemns sin,
then you are dead to sin and alive to Christ,
and it is "`no more you that sins but sin that yet remains in you,`"^
footnote:[Romans 7:17,20]
to which you are dead, and to which you do not consent, approve, enjoy,
nor in any way give your strength to.
Instead, your faith and love, delight and strength is in the One who condemns sin.
He that truly is in this faith and love, by the power of its working,
shall see his enemies perish.
And by that faith and love, the Just One shall live in that creature,
and He will be condemning and killing sin till it all be done away,
and the new creature of God will be found alive in Him alone,
and will be presented to the Father without spot or wrinkle.

For this I have found: the Light which manifests sin in its first motion,
and judges and condemns it there, has the only power to kill sin before it is committed,
and so also has power to save from condemnation.
And this you shall find--that even as Christ does not live
unto justification where He is not believed in and loved,
followed and confessed, likewise sin does not live unto condemnation where it is hated,
condemned, and denied.
For where that spirit of wickedness is seen in the Light and separated from,
and judged apart from the creature (the creature joining in judgment with the Just One),
there sin will wither and Satan will flee, for there he has no kingdom,
nor a hiding habitation.
And whenever the Light is minded, and judgment has free passage and consent in the heart,
there it will search out Satan`'s hidden things,
and judgment will pass upon all his deceit--his root and ground, with his fruits.
Thus, by faith in Christ (and not by the strength of the creature) the strong man is spoiled,
together with all his goods.

For according to every man`'s faith, so shall he receive from God.
Now, he that believes in salvation, and yet cleaves to and lives in some sin,
and pleads for it, and believes he must do so, this faith stands in an unclean thing,
and unclean things will continue to live in this sort of faith,
and be justified by that man.
And wherever man is approving or justifying anything that is unclean,
there he condemns the Just One who should give dominion over all that is unclean.
And so the wild plant has its liberty to grow until it overspreads the plant of God,
and covers the man, wholly stops his ear, blinds his eye,
and hardens his heart against every motion to good, or every check for evil.
This man should not look for any good fruit,
or think that such a faith will be counted for righteousness.

But on the contrary:
He that feels a strife in himself between the clean and the unclean,
and sees the one reprove for sin, and the other plead for sin,
and yet believes in that which is pure, clean,
and just (which condemns all that is unjust and unclean)
--this faith stands in that which is pure,
and "`the mystery of faith is held in a pure conscience.`"^
footnote:[1 Timothy 3:9]
And if this pure faith is followed,
it will purify the heart and cleanse the hands from unjust actions.
It is by this faith that the just shall live, and grow, and spring, and bring forth,
and the pure plant spreads and covers the inward earth with the knowledge of God,
His holiness, power, purity, and grace in the heart,
which is like the working of leaven till it has wrought out the unclean nature,
and conformed the whole man to himself.
This is a work of the holy faith, which none can receive but he who believes in holiness;
for none can bring clean fruit out of an unclean faith.

And this I have further to say,
for the encouragement of such as honestly desire to be rid of their sin,
and set free to serve God in holiness without deceit:
When you feel in yourselves the moving of that Seed which is holy,
bearing witness against all that is contrary to holiness,
and condemning it (and condemning you for joining with it), then, I say, _believe in that,_
for that is Christ in you.
Believing and following it,
you will feel it making a separation in your inward man
between that which Christ comes to save,
and that which He comes to destroy.
Yes, this is He that comes from above to set before you life and death divided,
so that joining to the life and believing you may be saved from death.
And as you are faithful to this Spirit which condemns sin in the flesh,
so you will feel a warring against, and a working out of sin daily.
And as you clearly join to this, denying whatever it condemns,
then you are one spirit with Him in his work, and are no longer in the flesh,
nor to be condemned with the sin that remains in the flesh,
but are one with Him that condemns sin (and condemns self in sinning),
until "`sin becomes exceeding sinful`"^
footnote:[Romans 7:13]
in your eyes, as it is in the eyes of God.
And as you grow to like and love that pure Spirit in all of its laws and leadings,
so you will become dead to the law of sin, and it will lose its power in you,
not being minded, loved and served; for your mind, love,
and fear will be exercised in that which condemns it.

Here the "`faith that works by love`"^
footnote:[Galatians 5:6]
takes the victory,
and not your striving in your own strength only from a sight of sin by the outward law.
For by the works of the law you cannot be justified; but,
by the working of faith in Christ Jesus, as you feel His Spirit working in you,
and as you are one with Him in His work, in this you are justified.
And in the beholding of Him by this faith you will be
changed into His likeness by His mighty power,
even by that Spirit to which you are turned.
And as He grows in you, and you in Him,
you will feel that power arising which will make you able to
give the "`answer of a good conscience toward God`"^
footnote:[1 Peter 3:21]
with lasting peace, and so by His resurrection you shall be saved from condemnation,
from which your own works cannot save you.

This work will go on with joy if your heart is honest;
for you will see the Holy One set before you, condemning sin.
And the beauty and holiness of all His motions will delight the honest heart,
and make the way easy to follow Him for the joy that is set before you;
for in all your tribulations, trials, and temptations,
this faith will present Him before your view.
Indeed, this made the saints of old endure the cross and despise the shame,
and bear the reproach, following the Lamb joyfully in all His leadings.

So you that love holiness, it is near you; power over sin and Satan is near you;
salvation is at hand.
Do not go forth to seek abroad what you have lost in your own house.
He is your salvation that condemns sin in your bosom.
He that reproves wickedness is with you; He that is pure is your peace;
He that never consented to sin but stands as a witness
against it--if you have such a Spirit in you,
you have the Spirit of Christ the Savior.
So take heed unto Him, believe in Him, mind His leading, and follow Him.
If you part not from Him,
He will be your everlasting peace and an overruling power to subdue your sins.
By Him you shall tread down the enemy`'s strength with ease and delight,
and shall be able to say with those who have come to the same Spirit,
"`Greater is He that is in you than he that is in the world.`"^
footnote:[1 John 4:4]
Only the faith that sees Him has power to overcome the world,
for he that beholds His glory treads the world`'s glory under his feet.
And whatsoever is seen in Him does so far exceed all other things that it
takes the mind out of all other delights and leaves them empty;
so that neither things in heaven, nor things in earth,
principalities nor powers are able to separate from the love of Him.
And how much more will you leave your delight in sin when you come to delight in Him!
Yes, love will constrain you.

And this is joy indeed, and love unspeakable,
when the soul finds that treasure in his own house
freely given which he has long been seeking abroad,
and could never purchase neither with life nor estate.
And the more you behold Him, the more His glory and love will appear.
In His Light you will behold the pure motions of the Holy One,
and will come to see what you are without Him, and what your true needs are,
without which you cannot be happy.
And you will see that you cannot have lasting peace till His virtue has filled you,
and His glory has covered you, and His power has armed you against every temptation.
All of this He will make you to inherit with Him as you continue faithful,
and hearken to His movings to obey them in all things.
He will thereby lead you in His way, the way by which He obtained all glory and power,
and the inheritance from the Father.
And keeping in this way, you will find a cross to all your own ways,
and to the world`'s spirit in all things,
which will be easy if you keep your eye single to Him who is set before you.

But if you look back into the world, you look into temptation without Him,
and there the spirit of the world presents you with all that you will lose and not gain,
setting before you what you must forgo,
with all the hardships and impossibilities that may be, and you see no power to bear it.
But keeping your eye to Christ,
you will always have power and peace before you in your way,
and the hope thereof will be as an anchor, and the faith as a shield,
and the love will give you life to undergo all trials for His sake.
And bearing His cross daily, it will divide you from your sins,
and crucify the worldly spirit with the lust thereof,
and kill all that yet wars against your soul and keeps you from your inheritance--
thus the cross is called the great "`power of God unto salvation.`"^
footnote:[Romans 1:16]

And as you become faithful to this cross,
you will feel the fruit of the Holy One springing up in you,
moving and being brought forth in you towards God and towards man.
Your faith will grow, and your prayers will be with strong cries to the Father,
as the Spirit sees your needs.
Your love will spring up and move in you, and flow towards God and man upon all occasions.
And if you willingly serve it in its smallest motions, it will increase;
but if you quench it in its movings, and refuse to bring it forth,
it will wither and dry up in you, not being exercised.

The same is true of gentleness, meekness, patience,
and all other virtues which are of a springing and spreading nature,
wherever they are not quenched,
but allowed to come forth to His praise (who is their Author), in His will and time,
and to the comfort of His own Seed.
And if you are faithful daily to offer up your body as a sacrifice,
in order to bring forth His image, name, and power before His enemies,
then what He moves you to bring forth shall be your inheritance,
and it will daily increase with the using.
But if you will not give up for His name`'s sake,
but would hide the treasure and escape the reproach,
then it will be taken from you and given to him who will yield
the Lord of the vineyard His fruit in due season.
For that which the Father freely begets, He desires to freely bring forth an increase,
so that its shining in the dark world may praise Him.
What a glory it is to see peace shine in the midst of war, love in the midst of hatred,
meekness in the midst of strife, righteous judgment in the midst of wickedness,
innocency in the midst of violence and oppression.
Yes, even as a lily among thorns,
that which is of God does shine among the men of the world.
And in this way His nature and beauty does appear in His temple,
to which all must confess and give praise.

This is the righteous Day which many have talked of,
but the children of the Day are those only in whom the brightness shines forth.
So then, that which God begets in you is His Son,
and you must confess Him in the midst of his enemies,
and thereby will the Father be glorified and his Son crowned.
But if you deny Him your body to testify against the world,
He will deny you His life to redeem you from the evil of it.
But the breaking forth of the Son is the beginning of the good day,
when that which so long has condemned you for sin
begins to shine forth freely in acts of righteousness.
Then is your darkness turned into light, your condemnation into peace,
your sorrow for sin into rejoicing in holiness.
This will be a good day to you,
even the Day of the Lord`'s righteousness and redemption to your soul,
and a witness to all men of the appearance of the Just One.
And whoever refuses to bear this testimony, all his religion will prove in vain,
and consist of words without power.

There is a way in which the barren one becomes fruitful,
and a little is more serviceable to God than the one who has great riches for himself.
You who see your lack are near it, and the lowly of mind will more readily follow it.
It is prepared for the honest of heart, who seeks to serve God, and not himself,
who takes heed of his own ways,
being careful not to form anything in the mind to offer to God;
for God will be served by His own begetting in you.
Take heed therefore that you make nothing out from yourselves,
nor murder that which he freely begets in you.
But let your minds be always heavenly,
waiting with patience in that light which lets you see your poverty,
so that your hearts may be open always,
turned upward towards God the Father of every good gift.
In this way you will be hid in the heavenly mind from the
nature which encompasses the earth in its dark comprehensions,
and desires to encompass heaven also.
Wait in the cross to that mind, and as you come into the patient stillness,
you will feel the begettings of the Father stirring in you to be brought forth.
To this you must become a servant, setting aside all subtlety, and all that is hasty,
and whatever is your own, or has an end to yourselves.
And experiencing a measure of the pure mind,
behold what way it moves in its appearance against the worldly spirit, that,
with your whole heart and might you may bring it forth in its own image,
without reasoning or consulting with anything of your own, or anything of this world.
For these begettings of the Father arise in a contrary
nature to that which is one with the world.
They bear another image and fruit, and have another glory in their appearance,
in which the Father alone is glorified,
even in the Son of His own free begetting and forming.
Herein is the Father glorified,
in that Christ is brought forth with His fruits into the world,
by which it may be known how far He is above and contrary to the worldly spirit,
both in His ground, root, and offspring.

And whosoever will give up themselves to serve Christ herein,
by His increase shall become rich towards God,
and increase in strength daily against the world.
And by bringing forth a new creation, and by His beauty in holiness,
you shall become glorious and beloved in the sight of the Father,
whose image and begetting you bear,
and in which you shall become heirs of the eternal glory.

But if you look back into the earthly mind,
there the worldly spirit will meet you with his counsel;
and consulting and reasoning therewith,
you will take counsel in the night where you cannot find the counsel of God,
nor see His work, or end, or glory.
Instead,
you will be presented with the pleasures and glories of
this world which stand in visible things,
and are pleasing to the visible eye and senses,
which glory the god of this world sees into, and leads into,
and in which his wisdom and knowledge stands.
And in this spirit that knows not God, nor His works, nor seeks His glory,
you will meet with the thief and the murderer, the sons of darkness,
who will strongly persuade you to murder the pure motions of Life,
and not to bring them forth.
Or else they will persuade you to bring forth a marred image,
which is not a clear and perfect testimony against the world`'s kingdom, power, and glory.
This you cannot avoid if you look back to the world`'s counsel,
and consult with your own reasonings, from which arise the thoughts, cares,
and pleasures of the world which encumber the mind, choke the Seed,
and cover the Pearl with earthly affections and lusts.
This continually hardens the heart, and strengthens the will against the innocent Life,
"`crucifying again the Son of God,`"^
footnote:[Hebrews 6:6]
refusing to bring Him forth in His time, and according to His motions.
And having rejected this, you cannot beget Life again of yourselves,
nor in your own wills, though you may procure a likeness of it from another spirit,
and in that nature which resists the truth and corrupts the mind,
and brings forth its own will.
Indeed, many have gone this way, who,
having disobeyed the still motion of the meek Spirit, and looking for higher things,
God has given them up to a lofty spirit, and to the strong workings of a contrary nature.
These now have a power wherewith they resist that which calls them out of the world,
and they have a spirit which draws towards the world again.
And this spirit, having gotten into the temple of God, is worshipped there as God.
To it they yield obedience, and so become the same as they were, if not sevenfold worse,
without hope of recovery.

Therefore, in the fear of God, you must watch with all diligence.
Hearken in the simplicity of your hearts,
and take heed that you do not slip and cease to listen,
or bring forth any false conceptions.
But "`be diligent to make your call and election sure to you,`"^
footnote:[2 Peter 1:10]
not only by having the knowledge of it, but also by bringing it forth,
that it may be yours forever.
For that which you bring forth of the Seed is your inheritance,
and none can take it from you; and in it you have power against all contrary spirits.
While the Seed is still in the ground, these spirits will strongly tempt you,
and seek your Life to stifle it.
But when the Life is brought forth, it remains before you,
and is put on as a breastplate,
and becomes a defense to set you over the head of the evil one.
But if it is not brought forth, it withers, and becomes as dry bones in the womb.

Therefore, even as you give your minds wholly to hearken,
so you must give your strength wholly to obey.
And when you feel His purity move in you, serve it with your whole strength,
and bring it forth.
Give up your bodies as a sacrifice for His sake (whom you have not seen),
that His life may be made manifest in your mortal flesh, and through you to the world,
that He may be seen in His brightness by all that love Him, and also before His enemies.
Then you will find that "`the body is for the Lord, and not for fornication.`"^
footnote:[1 Corinthians 6:13]
But if you rest in the knowledge of this mystery, and do not bring forth the Life,
with this knowledge you commit fornication, and teach others to commit fornication also.
This kind of knowledge in a disobedient mind becomes
the mother of harlots and fornications in the earth,
with which the kings of the earth are deceived, and none are thereby joined to God.

For it is not the hearing of the truth that purifies the soul,
but the obedience of truth which makes the vessel fit for the master`'s use.
And by His using it, and its obedience, it becomes a vessel of honor to glorify the Son,
and to do the Father`'s will in the world.
In this way, the Father is glorified in the Son, in whom He shines forth,
even as the Father begets Him again in you, and you in Him,
who was with the Father before the world was.
And as His life is brought forth by faith and obedience,
you will be changed into the same image and nature, and delight only therein,
being born of the same Spirit,
even as he that is born only of flesh delights in the things of the flesh.
