[#ch4, short="A Door Opened to the Imprisoned Seed"]
== Chapter IV. A Door Opened / To the Imprisoned Seed in the World

[.chapter-subtitle--blurb]
And the way of freedom sent out into the world by the Spirit of Truth,
in love to the sheep that have long been lost;
to serve all the simple who seek the life of what they profess,
and to show the proud and false in heart the
cause why they are shut out of Truth`'s power.

[quote, , John 8:32]
____
"`And you shall know the truth, and the truth shall make you free.`"
____

Every creature born of corrupt nature has that
spirit in him which lusts against God,
and that seed in him (growing up with him) which daily seeks
to ensnare his soul further into wickedness and vanity,
and to increase his separation from God by drawing into iniquity and
filling the temple (where God should dwell and be known) with the
accursed things which God hates and cannot behold.
This evil seed, being subtle and ambitious,
often prevails above the pure Life in the heart,
and leads the mind out from it into many temptations,
presenting it with delights to the carnal part and the outward senses,
whereby the Seed of God becomes ever more veiled and hidden from the creature.

It is because of this,
that man knows not that Word of life by which he was created,
nor can he come to be guided by it in himself,
till the head of this evil seed be bruised through
believing in that light which comes from the life,
by which the world was made.
This is that Rock which follows man with its unchangeable testimony,
faithfully bearing witness to that which is of Himself,
and against all the ways of the evil seed.
It calls to and reproves the world because of evil,
and as many as receive and hearken to its call by faith come to hear the Word of life,
wherein power is received to become the sons of God.

Now as the power of life arises in the promised Seed,
then the head of the evil seed is bruised,
and the one who had taken the soul captive at his will into
every vain and evil work thus comes to be brought under.
And as the created soul comes to be redeemed out from under the power of darkness,
so it comes to be guided in the light of that life by which it was created.
And now being turned to God by faith and obedience,
that light which before reproved him for deeds
of darkness (following him from one to another,
and condemning him), now becomes his leader out of the world, to the Son of God,
in whom God`'s righteousness is revealed unto justification.
And as righteousness is received and abode in, sin is remembered no more,
and man is changed into that divine nature which changes the inward man.
So he comes to love that light which before he could not love;
for no man can love that which is of God until he has first received God`'s love.

Now the Light of the world is God`'s love to the world;
for God so loved the world, even when it was in the power of darkness,
that He gave His Son into the world as a covenant of light,
that whosoever follows Him should not abide in darkness but have the light of life.
Now God`'s love stands in Christ--the Light of the world;
Christ _is_ His covenant with the world.^
footnote:[See Isaiah 42:6; 49:8]
And whosoever rejects and does not receive Christ, the Light,
this one is out of God`'s love, out of God`'s covenant, and remains in the enmity.
And this is the cause why men who love their evil deeds speak evil of the light,
and cannot receive it as God`'s love, nor as the way to life;
for to such it is their condemnation--not that it was intended for this purpose,
but to men loving darkness rather than light, it becomes condemnation.
But to him that believes and is obedient, to this one it is precious;
for whosoever follows the light out of the evil world receives the nature of sons,
the love of the Father (which the world cannot receive), the power of godliness,
and the treasure of eternal life.
These are not given to any till they come out of the world,
even as He is not of the world,
for therein stands God`'s covenant with Abraham`'s seed forever.

So while men remain in that corrupt nature, God`'s love to the world,
and the witness of the Spirit of truth, is to reprove the world of sin,
and to testify condemnation against its deeds.
But to such as have received His light, the same becomes their leader, comforter,
and Savior.
And this is the cause why the one loves, and the other hates,
for each nature manifests the state in which it stands towards God,
according as it has obtained from Him either love or condemnation.
And whoever will not receive God`'s love (which calls him out of the world),
must abide under the power of that seed which God hates,
in which condition he will seek to murder those who stand in God`'s love;
for the evil one, having blinded the mind which denies the light,
gives him to think he is doing service to God.
Alas, this is the sad end of all professors of Christianity who reject the Light of the world;
for he that walks in darkness knows not where he goes.
God is light, and in Him is no darkness at all, nor has darkness any fellowship with Him.
And in this are known the children of God and the children of
darkness--he that loves the light brings his deeds to the light.
This one has fellowship with God in his deeds, and works the work of God.
But he that denies the light works in the darkness,
and cannot believe the power that is in the light,
being himself under the power of darkness.

And therefore he that is born after the flesh does not
know him that is born after the Spirit of light,
nor can he judge his ways, which are strange and wondrous in his carnal sight.
Nor does he know by what power and love the sons of light
overcome the world and take delight in denying its pleasures,
and vanquishing all its vanities out of their heart and mind.
Indeed, these can no longer rejoice in the world, nor make merry with its amusements,
but instead rejoice in the truth,
and are made glad by that which saves out of such folly.
The wicked know not the life of the righteous,
nor the Spring from which his virtues arise, nor the power of his change,
nor the end of all his patient sufferings and trials,
but stand wondering at all this as though it were folly and madness.
For the eye which would give them a sight of
these things is blinded by the god of this world,
and the soul being in bondage under the prince of darkness,
cannot inherit the immortal treasure.
And this must be,
until there is a denying and coming out of the world to
receive the inheritance of divine light and understanding,
which none can receive nor become one with, except as they come out of the world,
and out from under that seed of enmity which seeks to pervert all the right ways of God,
and to twist all His gifts to man`'s destruction as far as he can prevail.

Now this destroyer (or seed of enmity against the life
of man and his salvation) is kept from a sudden effecting of
his purpose upon the creature in whom he is head,
by nothing more than the patience and long-suffering of God,
who wills that none of His creatures should perish,
but that all might hearken to the truth,
and so recover themselves and be saved out of the snares of this subtle deceiver.
Thus does God often bear and forbear with man.
With much patience and striving by the Spirit of truth, He checks and reproves and warns,
even at the very instant when the act of sin is being committed.
And if the evil one has gained such power in the creature so as not
to permit him to mind reproof before or in the act of sin,
then afterwards, when the heat of temptation is cooled,
then God shows the evil and danger of such wickedness,
that so he might preserve him in fear against the next temptation.
And thus (in many) the Lord keeps back destruction a long time,
so that some continue a long time before the wicked one
gets them to fill up their measure of iniquity.
And some, in the time of God`'s patient forbearing and long-suffering,
come to repentance and turn to that which reproves them and are saved;
but others go on to destruction,
which they swiftly draw upon themselves after the
Spirit has ceased striving with them and reproving them;
for then all fear is lost, and the evil one has his liberty according to his own will.
Yes, when the creature has been given up by the Lord,
and the Spirit of truth has departed,
there is nothing but deceit left to guide the soul that
has dealt deceitfully with the Spirit of truth.
Such a one, at best, has but a form of godliness without the power;
for the power of God is in that Spirit and life
which is known by withstanding the evil one.
Only those who are born of the Spirit have the life and power,
and know its strength and virtue unto eternal salvation.
But this Spirit is hidden in those in whom death reigns,
and they are left to their own thoughts and notions.

And this is the cause of the strong contention that has ever
existed between the children of light (who are born of the Spirit of
truth and have their light and strength in the inward man),
and the world`'s professors of religion,
whose expectation stands in something outside of them,
about which they have only heard others speak who had it within them.
The latter,
not knowing the power and mystery of the living
faith (which is held in a pure conscience,
and which alone has the power to bring out of the world`'s darkness),
are kept captive therein, contending against the spiritual light.
And so, while these continue in the world,
they go about seeking to comprehend and measure the
Spirit of truth (which the world cannot receive or know)
assuming that this Spirit of light and life has no
other operation besides what they find in themselves.
Thus they stumble at it and are disobedient and unbelieving in heart.
Now, to us who believe, it is the elect and precious cornerstone,
and we come to it for all of our supplies.
But to the wisdom and religious profession of the world
it is a rock of offense and a stumbling stone,
though it witnesses in their hearts in secret, and leaves them without excuse.

Those who reject this light and Spirit have nothing
else that can show them so much as one of their thoughts,
or divide in their understanding between evil and good,
either in thought, word, or action.
These cannot discern between what is really of God,
and what is of him who shows himself to be God (but is not) in order to deceive;
nor can they perceive the various motions of every spirit that is in them,
to receive the good and deny the bad; nor can they know the roots of life and of death,
or which plant to pluck up and which to feed upon.
And how can such as these labor in God`'s vineyard?
Indeed, without obeying this light the body is a house of
darkness and a habitation of every deceitful spirit,
where the heart remains desperately wicked,
and no man knows it but he in whom the light of truth shines.
But He that declares to man his thoughts, His name is the Lord of hosts.
This one is the true Cornerstone who the stumbler cannot comprehend by his wit,
and so rejects Him; but without Him there is no true building or working the work of God.

Therefore, you sons of the darkness of this world,
take care what you set yourselves against!
Are you not opposing that light which would limit and chain the evil one in you,
which also condemns you for every evil work (both secret and open),
and will not let you be proud and loose and lustful?
Is it not the light in your own hearts which testifies against
you for deceit and falsehood towards God and towards men,
for deceit in religion, hypocrisy and falsehood,
and for making a form of what you have not personally witnessed?
And does not this light expose all deceit in your dealings with men,
in your trading and speaking and acting, both as rulers,
priests and people without respect of persons, or any other thing?
Yes, it has respect only to that gift of God in you, which is of His nature,
given to you to guide you in the light of God,
out of all the ways of the deceiving spirit.

And now, if one comes to you preaching this doctrine,
he is made manifest in spirit to that gift of God in your own hearts,
and you are pricked by it in the heart.
But then the evil one is stirred up to fight against the measure of truth in
you (which acknowledges the truth that was spoken to you by another).
But rejecting this,
you join to the evil one who rises up in wrath against the witness of truth in you,
and so you deny the very thing that would chain and bind him.
Yes, you deny the Lord of life,
and give strength to your enemy to crucify the Just One in you,
and to quench the Spirit of Truth, and weary the Lord with striving,
till at last you are given up wholly to the power of darkness,
who will then keep you seeking salvation without,
even while he is heaping up evil within.

For that which seeks to devour your souls is within you,
even while the enemy keeps leading you outward to seek salvation.
Nothing can condemn you but what is within you.
Sin is within before it is acted, and so salvation must be within before you are cleansed.
The old deceiver has taught people to think they
are saved by a mere belief in God at a distance,
but these neither know Him nor worship Him in Spirit and truth,
nor are their bodies His temples, nor can the Holy One dwell or walk in them,
because of uncleanness.
Indeed, their vessels are filled with the powers of darkness,
and the heavenly place is an abode for spiritual wickedness,
so that God departs from the children of men because of their uncleanness.
Even so, the liar continues to speak peace and preach salvation,
and the creature believes it, being filled with darkness.
But the children of light do not receive this doctrine, for they can see and feel,
and so are not content with words but with power.
A talk of God does not satisfy the soul of a good man,
until he feels His presence and power.
God without and the devil within is not the saints`' faith or salvation;
but God within and the devil cast out is the saints`' true glory and strength,
and they are made bold through the might of His Spirit within
them to war daily against the prince of this world,
knowing that, "`He who is within them is greater than he who is in the world.`"^
footnote:[1 John 4:4]
This is the faith that overcomes the world,
and he that is born of the Spirit has the Father and the Son.
But he that has the devil is God`'s enemy and knows Him not, nor where He is,
but judges Him after the flesh and according to outward appearance.

Now consider, were men not entirely blind in their minds and "`past feeling,`"^
footnote:[Ephesians 4:19]
they could never sit down believing they are saved even
while they are daily captivated in sin,
and often led to do that which they know they should not.
Indeed, this leading is by the power of lust, enticing and moving into every temptation,
and causing the soul to fall into many hurtful evils,
which put down roots and gather strength daily in them,
heaping up wrath and vengeance by adding sin unto sin.
And truly, all of this must be accounted for in the end,
when each has filled their vessel to a full measure.

And consider,
can you say you are redeemed from the devil while he still has
this power in you which you are not able to resist,
but are led captive at his will, contrary to all fear of God or power of righteousness?
Are your bodies redeemed to God,
and are you members of Christ even while you yield your members unto unrighteousness?
Are you saved even while you are servants of sin?
In what does your redemption, your faith, and your salvation stand,
seeing that nothing can stand with God but that which brings forth His nature?
Is not the one who brings forth iniquity still in the bonds of iniquity?
Is not he a servant of sin in whom sin reigns?
Is not he a child of bondage,
who is bound to bring forth whatever the evil one begets in him,
and to serve him in what he moves him unto?
Mind this,
you who are born after that fleshly spirit who works in your
flesh to do his will and bring forth fruit unto death!
Does your profession save you, though you are not turned from dead works?
The foundation of repentance is not yet laid in you, and therefore death reigns over you,
contrary to the life which would bear fruit unto God.
Truly, this is the state of the servant of sin, in the spirit of bondage,
and not the state of the heir.
The one inherits God`'s righteousness and brings
forth the fruit of that Spirit which pleases God;
the other brings forth the fruit of the flesh which pleases the world.
These two seeds are within man, and are at enmity and disagreement,
and there can be no concord between them, no more than between light and darkness.
Their various fruits are made manifest by the light,
which condemns the one and confesses the other to be of God and wrought in God.

Now, as many as are quickened with the Spirit of life have a feeling of
these things before they bring forth their fruits into the world,
for they have come to a discerning of things that differ in
nature and effect by tasting and handling the Word of life,
and knowing the election which is before the world was.
By this they are made able to judge the ground and the end of every motion in them;
and abiding in this, they need no man to teach them, neither can they be deceived.
And this makes them boldly and openly bring forth such words
and works as are begotten in them by the Word of life,
which show the whole world to lie in wickedness,
and make its wickedness manifest by the light of life.
And in this light the prince of this world is judged and condemned,
and the secrets of hearts are made manifest according to the nature of every spirit,
for all comes to be seen in the Day of the Lord`'s appearance.
Yes, to this Spirit of Truth all flesh must give an account--to Him who lives in
all generations as an unchangeable witness against the evil seed,
however he may transform himself in words and professions.
For there is no agreement between their two natures, be it in a person, a family,
or in a nation, nor can any one person, family or nation serve them both;
but whoever serves the one hates and condemns the other.
So that, he that serves deceit condemns the Just One,
and so condemns that which could save him and that which must judge him in the end.
This is the cause of that fleshly liberty which some presently feel, namely,
that the Witness of God is crucified in themselves.
But these will find horror of conscience when the Just One appears for judgment,
manifesting the unstable state of all who are not faithful,
but revealing the everlasting peace and power of those in whom Christ has dominion.
Then the fruit will be seen of those who are presently in sorrow,
who are diligent in waiting and wrestling (through faith and patience)
from the beginning of the work of Christ Jesus till the end.
All these things are comprehended by the one who has learned Christ,
through being faithful to the Spirit of Truth who is sent in His name
to testify concerning what is of Him and what is of the spirit that
lusts against Him and keeps the creation in bondage.

This is the one way to life and salvation held
forth freely by the Spirit of Truth,
and sent forth by the Father in the name of Christ Jesus.
For the Spirit has several operations in different
vessels according as He finds them towards God.
In some He is a condemner, in some a leader and teacher in the things of God,
in some a perfect justifier in the sight of God,
and in some a giver of gifts and power to such as receive this testimony of Jesus Christ.
Nevertheless, He is but one in all, unchangeably just, equal and holy,
who by the power of His Word changes all things that are changeable,
and brings all things back to the beginning--before people,
nations and tongues were divided--where man lives by the Spirit of a pure life.

Now, all that desire to be set free from the bondage aforementioned,
and from the law of sin and death that has its strength in the fleshly part,
diligently mind and seek to feel in yourselves what follows:

The Spirit of life which is in Christ Jesus,
by whom the world was made in the beginning, has a law that is spiritual,
proceeding from Himself, which law sheds light (in spirit) on good and evil,
and testifies against the power of sin and death.
As many as receive this light by faith and obedience
are brought thereby under the law of life,
and those who are faithful to it are led in a way whereby the fleshly
part in man (where sin has its power) is crucified and slain.
In this way,
the Seed of the covenant comes into its proper dominion and freedom in the soul,
which before was kept in bondage by the man of sin.
For while the strong man keeps the house,
his strength is in such things as the carnal mind takes pleasure in.
But the law of the Spirit calls men from these things,
and all who mind its light are led to fix their minds
on spiritual things and to feed upon the Word of life.
Thus the inward man is strengthened and made to
grow up into the stature of a spiritual man,
filled thereby with spiritual power, life and virtue, to bring forth fruit unto God,
and to live to Him,
even as the other man lived to the flesh and brought forth fruit unto death.

Thus the Spirit of life draws men by the light and says "`Come!`"
All that mind His voice, and as many as hear and obey,
He changes and feeds with new life, whereby they become new creatures,
born of the Spirit.
But the fleshly spirit also draws,
and says "`Come!`" holding forth visible idols to win the carnal affections,
and to captivate the mind from the Spirit of life into carnal objects.
These promise much to the eye of earthly wisdom,
and have a likeness of the substance in them, but their end is death,
and those who obey this call pass their life in
captivity to vanity and separation from God.
So then,
here the children of freedom (which is in Christ Jesus) are
made manifest to the world by their coming out of it;
and the children of bondage are also made manifest, for they cannot cease to serve it.
And between these two there is no agreement;
for he that is a servant of sin is free from righteousness,
and the servant of righteousness is free from sin.
And just as he that is in the flesh cannot please God,
neither can he that is in the Spirit please the world--for
these are children of opposing kingdoms and contrary natures.
And he that is born after the flesh has that spirit
which lusts enviously and seeks to devour the creation;
and he that is born again after the Spirit of life is brought into the restoration,
as it was in the beginning,
and brings forth to God the fruits of eternal life and salvation.

And as it is by the creature`'s yielding and
consenting to the subtle one that the life is lost,
and the evil seed gets strength in man to rule and
bring forth fruit according to the power of darkness,
so too, by the creature`'s believing in the light,
and yielding to the motions of the life and law of holiness,
the evil seed comes to lose its strength and its ability to feed upon carnal things.
So that life which is by faith comes again to be renewed in the vessel,
and it arises through the Spirit and reigns above death.
The righteousness and virtue of this life are
clearly not of the nature of flesh and blood,
but rather the nature of God,
and these things are made manifest in the earthen vessel by the power
of the Spirit against the will and lusts of the flesh.
Thus man comes again into the restoration and redemption of the body,
and into the free service of that Spirit and life of whom he is the offspring,
and for whom and by whom he came into the world.
Here there is no condemnation, but a true reconciliation and peace with God,
and unity in Spirit and life, even as the Father and Son are one.
For here the lusts are slain, the enticer is denied, the accuser is cast out,
all things are become new, and all things of God.
Here man is no longer in a house of bondage to sin,
but in the glorious liberty of the sons of God,
where the spiritual nature that is quickened in him does not
feed on carnal pleasures but upon the living God.
In this way the inward man becomes a natural branch of the holy Root,
and a plant of the living God, bringing out freely whatever the Root sends forth,
by which God is glorified, the vessel made honorable,
and the soul filled with peace and fatness,
having no more sorrow and death to oppress it.

Now, to know the light and life which are in Christ Jesus
and are made manifest by the Spirit of truth,
this is both the first and the last in this great work.
And by this light, it is seen how unnatural man has become, being driven from God,
away from that pure life which gives him breath and
being and would preserve him from destruction.
Yes, man has fallen so entirely from this,
and become contrary to it in nature and judgment,
that of all things in the world it is his greatest cross to be
guided by that light which arises within from that holy life,
and daily calls to him in spirit.
And having degenerated into a contrary nature which is subtle and selfish,
he is made willing to join with the enemy in any way against
the witness of the pure light within him--either to revile,
reproach, or crucify its appearance,
turning light into darkness by covering it with deceit.

But apart from this light,
there is nothing else within a man that is holy and just,
or that calls him from the paths of the destroyer into the way of life,
or brings forth through him any fruits of obedience or
spiritual worship which God will accept.
There is no other thing that is always present with man,
to show him when he is enticed with lusts and tempted to sin,
or the way to escape the temptation.
Yet man is so exalted in the contrary nature that he has forgotten his Creator,
and lifts up his heel against the reproof of His Spirit,
trampling upon the lowly motions of the Holy One
and the law which proceeds out of His mouth,
counting the light and virtue of His life to be a low and contemptible thing,
not able to save.
Thus does lost man daily despise the Spirit of grace and truth in his
inward parts and reject the Holy Spirit to the hurt of his own soul,
denying that pure and single eye by which the holy men of God saw, discerned,
and spoke in all ages, as the Scriptures do testify.
All of this is lost to that man who is exalted above the pure light and lowly
Spirit in which God meets with man to teach him the knowledge of the truth.

Therefore, you teachers and people of all sorts and sects,
who so violently have set yourselves against the
light of the Spirit both within you and others:
how long will you kick against that which pricks your heart
for your ungodly walking and pretended professions?
Why will you not be still and commune with it in your own hearts,
that you might come to a true feeling, and discern what nature it is,
and from where it comes, and how it works, and against what?
You will also see what nature it is in you that
the light chiefly condemns and works against,
and from where it comes.
Thus, with the light of truth you will come to judge between
things that differ in their ground and end,
and so come to walk in the light, in judgment,
and in truth of heart towards God and man.

Now, let the truth of God in you (without any mixture)
feelingly answer these following things:

[.numbered]
1+++.+++ What is the cause that, while professing to seek God and serve Him,
you are so unwilling to serve Him in that which is of His own nature,
and to worship Him in Spirit and truth, in your own vessels,
whose bodies should be the temples of God,
who is not worshipped in temples made with hands nor in a nature contrary to Himself?

[.numbered]
2+++.+++ Will a mere talking of what God is or was in others (in whom He
was formerly known to walk and speak) deliver your souls from the
power of the prince of darkness and deceit that is in you,
unless you receive Him even as they received Him,
and feel His power overcoming and casting out the one who has taken
you captive to do his will against your faith and conscience?

[.numbered]
3+++.+++ Will God be found by you,
or will He accept your worship while His temple is possessed by His enemy,
and a contrary nature moves you therein?
Can you meet with God in anything but that which is holy,
knowing He hears not the prayer of the one who regards iniquity?

Therefore, your first work should be to know the One in you whom God accepts,
for He alone (who appears without sin) must present you to the Father,
else you are reprobate in God`'s sight.
For there is no hope without knowing Christ in you and you in Him,
the everlasting Priest, to make the offering upon the altar of atonement.
And though because of the height of your minds He that
is without sin may be low and little in you,
yet "`without Me you can do nothing,`"^
footnote:[John 15:5]
says Christ Jesus.
Mind what He says, "`You can do __nothing.__`"
What are you doing then, who are not in His Holy Spirit?
Can you worship by tradition, or be saved by the letter?
Will you make Christ a liar, who says,
"`Without Me you can do nothing`" and "`I am the light of the world,`"^
footnote:[John 8:12; 9:5]
and "`Every branch that abides not in Me is cast out and withers,
and is burned in the fire`"?^
footnote:[John 15:6]

Mind this, you who reject holiness in spirit,
and the light that shines from the Holy Spirit within.
If you abide not in what is holy, are you not cut off?
Are you not withered and prepared for the fire?
You who have no abiding place in that which is holy, are you not cast out,
having power and knowledge to do evil, but not to do well?
Are you not cut off from the true vine and planted into a wild vine of a contrary nature?
Your light is withered, your seed is corrupted, and your tree is known by its fruits,
which now bears fruit but not unto God, nor from God.
Will you say "`you hope you are born again of the Spirit,
and are baptized into the Spirit, and walk in the Spirit,
and worship in Spirit,`" and yet look outward for salvation and for light,
and speak evil of that which is able to overcome the world?
For this reason your hope is not an anchor, nor is your faith that which overcomes.

The Scriptures declare, "`He who has been born of God keeps himself,
and the wicked one does not touch him.`"^
footnote:[1 John 5:18]
Now consider in yourselves:
where is He that gives you to see when the evil one touches and tempts you?
What nature is He that does this for you,
and where is He? Is He not light and understanding, and is He not within you?
And is He not of a contrary nature to the evil one that tempts?
And does He not show you the temptation before you consent to it (if you mind Him)?
So then, what is the cause that the evil is committed,
seeing the light appears against him?
Is it not because you join to the evil one,
and like his motions better than the One that shows them to be evil?
Thus you deny the holy and just One, and become one with the evil one.
And then you say, "`The light is not able,`" when you have denied it,
and have not been faithful to join to it in counsel and strength,
but have given your strength to the contrary spirit.
But they that are born of God`'s Spirit and light do not do so,
but when they are shown the evil one and his temptation (whatever it be,
or under whatever pretense) if the light testifies against it, then they are diligent,
watchful and sober, in the fear of God,
lest they should be drawn from the light and enticed.
With all their power they join in obedience to the way of the light,
so that there is a war and a wrestling before the thing is over.
But the enemy, being resisted steadfast in the faith, flees,
and the glory returns to God who dwells in the light.
And if at any time the evil one prevails,
then the creature sees the cause to be in himself and not in God,
and so is humbled and warned.
This he comes to see when the temptation is over and the enemy has fled,
and when he has come again into composure with God in the light;
for while the darkness was risen up and the enemy was in the house, he could not see it.

Thus experience is gained through tribulations and trials,
but they who do not endure the temptations never come to learn of God,
but fall through unfaithfulness to the light.
These are kept captives to the will of the enemy of all righteousness,
who always tempts to evil and reigns over the members--leading out the eyes, ears,
hands and heart to iniquity and vanity, and the tongue to plead for it,
against every reproof.
And having denied the reproof of the Spirit of truth within themselves,
the same cannot be received from others;
for the contrary spirit reigns alone in that house, turning the ear away from knowledge,
and the heart from spiritual understanding.

This is the cause why many are kept without the
feeling of God`'s power and the knowledge of His Word;
for the mysteries of His powerful counsel are revealed to the faithful,
who have overcome through faith and patience,
and in whom Satan is subdued and trodden underfoot.
But wherever this devourer has risen above in the creature,
whatever God gives or reveals is by him perverted to a contrary end,
which God never intended,
so that a wrong nature and a contrary spirit (which God hates) is lifted up and exalted.
This is evident in the light of truth throughout the world.
For what gift of God does the spirit of the world not abuse?
If God gives wealth, wherever that spirit has risen above,
there the creature is puffed up above the rest of his brethren,
as though he were no longer of the same flesh and blood.
If God gives beauty, it is turned into lust, pride, and wantonness,
both begetting and deceiving adulterous eyes.
Wisdom is turned into folly and wickedness,
scorning the innocent and outwitting the simple-hearted;
and those who have the most of it, are most able to accomplish their corrupt ends.
When God gives grace, it is turned into fleshly liberty,
and His long forbearance is made a cloak for sin and hypocrisy.

There is not one thing that God can give which this
evil one will not twist and turn against the Giver,
so that, though God is good and full of mercy by nature,
yet He will not show Himself to those in whom the strong man keeps the house.
This makes the creature even more shameless to kick against his Creator,
and puffed up to forget his maker and feeder.
Thus a fruitful land becomes barren because of the wickedness of him that dwells within,
though it was not that way from the beginning.

But it is not so with the children of light,
who have the Giver in their hearts raised up above the gift.
Here the pure counsel orders the gifts,
and every good and perfect gift is brought forth in its own nature, form, and manner,
undefiled and not disfigured by the spirit of the world.
Yes, here the springs run forth from the clean Fountain,
and both the plant and the fruit are holy like the Root;
for the spirit is clean and the flesh undefiled,
and everything remains as it comes forth from God.
In these vessels the old man is put off, and all things are of God,
and every gift of God is known by its fruits and nature and end,
as it was in the beginning.
Here the gifts of God return to God by glorifying Him here on earth.
Riches bring forth good and merciful works, and not pride and vainglory;
wisdom stands against oppression and does not deceive;
and righteousness reigns through grace unto life eternal.

The religion of these is pure and unmixed with the world,
whereby the sons and daughters of God are known in the streets by the garment of
virtue and decency with which they are covered--even the fruits of the Holy Spirit,
and the faith and truth which are in Christ Jesus.
These are the "`vessels of honor,`"^
footnote:[2 Timothy 2:20]
fit for the Lord to shine through against His adversary (the
spirit of the world) in fruits that cannot be condemned;
for here the gift is not defiled by the vessel, but manifest that it comes from above,
reaching to the witness of God in every heart.
Yes, these are sons of God without rebuke in the midst of an unclean generation,
shining as lights, honoring God, and answering the end of man`'s creation.
God does not withhold Himself from these, but is rich towards them,
till they come to be filled with the fullness of God.
But the unclean and slothful, who defile the flesh with their lusts,
from these He withholds His riches and fullness,
so that they do not know the sons of God, neither where they come from nor where they go,
who follow Christ out of the world,
never returning there again except to testify against it.
The vessels of these are no more filled with lust, or the spirit of this world,
but are filled with the Holy Spirit who has made
them new creatures for Himself to walk in,
and to shine forth in fruits of the Spirit.

And now, all you barren and earthly-minded professors of Christianity,
who have filled your vessels with carelessness, deceit, and a fleshly mind,
in vain do you hunt about with your old wineskins
thinking to retain the heavenly treasure.
Alas, you travel about in search of notions,
but it is to no purpose in the sight and esteem of God,
for you are in the wrong work while you remain
in the world`'s nature and in the old creation.
Your words and ordinances are void of the life of God,
and you cannot receive or bring forth His fruits until you are renewed;
for nothing you do will avail but a new creature.
Your old vessels are full of old wine from wild grapes,
and that which defiles the conscience is raised up in you.
Thus God withholds His gifts from you which abound in His new creation,
and you know nothing of them except what you feel to condemn you.
So you fight against Him and say there is nothing now perfect,
and so you condemn the new with the old and judge them alike.
Thus you err, not knowing the gift of God nor the works of His hands,
which are all perfect as He is perfect,
who walks not in a defiled temple nor lies in the bosom of harlots,
for these are outside of His power and have gone
astray from the perfect way of a holy life.

Therefore,
it would profit you most to take the candle of truth and sweep your house,
and cast out the old leaven with whatever is of the world.
Yes, you must wait in that which works in Spirit against all that is old,
until all is made new.
There is a new vessel which will not receive the old, nor mix with it,
but will only hold what is new.
This God will fill with Himself, that His Seed may spring up and not be hindered,
and His lily may grow without being choked.
Here the lamb may be safe from the wolf, and the pure kept from pollution;
for the plant of God is more pure and tender
than to grow while the pollution of a covetous,
proud, lustful, and earthly mind is alive in you.

So to judgment you must come first,
to acknowledge condemnation upon all that is old, before you can receive what is new,
or know its growth in you.
What agreement has the spirit of meekness with the spirit of pride,
contentedness with covetousness, holiness with lust, Christ with Belial,
light with darkness?
Read and understand, for here is the cause why you have sought and labored many years,
but have found no freedom, nor that rest which the thief and the unclean cannot devour.
Consider these things while they are near you,
lest your hearts harden through unbelief and the deceitfulness of lust.
Do not refuse Him that calls and gives you light in the dark,
but keep faithfully on the watch,
warring with all your power till all that He testifies
against in you is brought under His feet.
And when Truth calls, do not answer with deceit and excuses,
lest He turn away from you and call others more worthy.

If you say the world holds you back,
then it is time to break those bonds that have grown so strong already.
Do not delay, for they grow stronger every day, and what will the end be?
Consider and understand, and do not say you lack strength,
but turn with that strength with which you have long served the world,
and you will find God (who gave it you) to be the better master;
for the Redeemer is served with less vigor than the spirit of bondage.
Whatever strength you have received from God,
do but faithfully give it unto the service of God in the light;
for He requires no more than He gives.
It is deceit that makes these excuses in you, and not a willing mind;
and if you were in the fear of God,
you would not utter such words that do but witness against you.

Therefore, you who speak this way,
in truth of heart consider what state you are in,
and who is your father and has power in you.
Can you do evil with both hands, live for your lusts, serve the world,
travel the earth for your profits and pleasures, with power, wisdom, and delight,
and yet have no power to do well?
Oh, if you did truly love God and His true worship your hearts would be smitten with sorrow,
and you would find power to bridle your tongue, and limit your eyes from vanity,
your ears from pleasure, and your hearts from deceit,
that so you might only hearken to the light.
Yes, then you might hear the voice of Him that is sent into the
world to call you from under the power of Satan unto the
living God by preaching light to you who sit in darkness,
who are dead while you live.
For you cannot be quickened until you hear the voice of the Son of God,
which the deceiver keeps you from in your worldly pleasures and lying professions,
using the saints`' words to cover yourselves from true judgment.
For though you use their words, you do not have their Spirit,
nor power to live their lives,
nor are you plants of that root and nature which brings forth fruit unto God.

Therefore,
that nature in you which is so entirely unprofitable should be denied its will,
and its way should be stopped.
Yes, you must die to that seed which now rules and has strength,
and which runs to and fro to seek food for itself, but does not seek God.
And you must turn to that which is pure,
and wait therein for the anointing and the rising up of the holy Seed;
for without Christ you can do nothing.
That seed which is neither willing nor able is not His, but is the seed of the evildoer,
and is manifest by his fruits, his thoughts, his words, his profession, his prayers,
his lusts, his sin and his righteousness.
All of this is of one nature,
and it rises up in you to withstand the coming of the Seed of the covenant--Christ Jesus,
the life of God and the light of men,--who has God`'s power and righteousness,
which were in the beginning.

Christ`'s light will show you His law,
and the Spirit of prophecy will testify of His coming,
so that His way may be prepared before His face.
All of your crooked, perverse, and shameless ways must be made straight,
your hidden and subtle ways must be made plain,
and the refiner`'s fire must pass through your house and take hold on all that will burn,
until it is consumed.
For until the filth is purged out and an end is made of sin,
God will not dwell in His temple,
nor will everlasting righteousness be brought in for an inheritance.

Here you will come to learn the first principles of pure religion,
and the doctrine of the beginnings of Christ.
For here the foundation of repentance from dead works will be laid in your heart,
and you will see what kind of treasure your careless minds have treasured up
in your vessels by all your deceitful and unprofitable words and works.
Yes, you will see by that light which will not lie,
and find that all will fail you but truth.
Whatever you have gathered by craft and deceit
will now serve no purpose but to deceive you;
for truth in the inward parts must be your only stay.
And when all else is weighed and found too light to abide the trial,
to the Rock you must fly for refuge (though He is now lightly esteemed), that is,
to His light within that gives you the knowledge of God in the face of Jesus Christ.
Nothing outside of you will make your peace,
but only that which works in you and cleanses your house of your adversary.

It is by this that the holy men of God (who have gone before you in
the regeneration) have preserved a clean house and a pure conscience,
walking above all that the world can offer or promise,
having learned (in the day of trial) that all proves a lie but truth in the inward parts.
These learned of Him that none are true worshippers but
those who worship the Father in Spirit and truth,
and have found that the whole mystery of faith and godliness is learned within,
and held in that which is pure;
for only the pure in heart have seen and heard and learned of God.
Such as these are sons indeed, who are born of the Spirit, led by the Spirit,
and filled with the Spirit, having power, light, and understanding to do well.
Yes, these are temples of the living God, who is holy,
and are vessels of that Spirit which the devil is not able to resist.
And every true child of God has this in measure,
by which they resist the world and overcome it,
for "`whatever is born of God overcomes the world.`"^
footnote:[1 John 5:4]
God is faithful, and will not forget Himself.
Blessed are they who have a measure of that which God
cannot forget nor allow to be tempted beyond measure.
For in this alone is the election by which the soul is saved,
and in it the creature finds favor in the sight of God.

Therefore consider this,
all you who mock at a pure conscience and reject the gift of God within,
speaking lightly and reproachfully of it: If you knew who it is you reproach and mock,
you would rather bite your tongues than utter a word against Him.
You would change your minds and seek Him,
together with those that sell all they have to find the pearl.
And though this now seems little in you so that you dare not trust to it,
yet all that have proved it, prize it as the great power of God to salvation,
and find that they have no election but what is in it.
It was in this that Noah found grace in the sight of God when the earth was corrupted;
and in it he walked with God and was saved, being just and perfect in his generation.
And it was in this righteous Seed that Lot was grieved by the uncleanness of Sodom,
and by it he was saved.
So then, the election of God stands in that which was before sin, is grieved at sin,
and testifies in man against all uncleanness;
this was the elect Seed before the world was made.
It is this you must make sure unto you,^
footnote:[2 Peter 1:10]
but those who say they have no power to do well deny His call and so cannot do it.

He that calls you out of sin, and the part of you that is vexed because of sin,
is still little and low in you; but the god of this world is lofty, strong,
and powerful in you,
and has lifted up your heart on high to seek great things far above the pure Seed
of true light and understanding which God has chosen and elected to Himself,
and in which He communes with man, and teaches him His fear and knowledge,
and gives Him spiritual power and salvation from sin.
So now your lofty looks are too high for this door,
and you despise the day of the small and simple One,
being unwilling to wait for great things where so little is seen, for you have no faith.
Thus you run ahead of your rest, and the poor in spirit takes the kingdom before you,
to whom the election and blessing belongs.

Now consider the calling of God and His election.
Has He elected the rich in notion and high in profession, the proud and the extravagant?
Has He not chosen the weak and poor, the foolish and contemptible to confound all this?
Yes, He that is pure, meek, and holy calls, and the soul that is meek,
lowly and loves holiness, answers, obtaining grace to be holy in every manner of conduct.
Here the calling of God is made sure,
and the election is known by answering the call and keeping in the election,
which was in God before there was transgression.
But whoever denies the One that calls out of darkness
into light (by the power of His holiness,
lowliness, meekness and truth, manifest by the gift of His Spirit within you),
this one denies both the calling and the election,
to lay hold of something without and to cling to
a changeable thing where the election is not.
For the election, being the light and power of holiness and truth, is preserved in God,
even if all the world be deceived, defiled, destroyed, and changed.

Therefore come down off the mountains,
you that have lifted yourselves up on high without God,
who have a form of godliness without the power of God.
Feel after that gift which is pure, lowly, and righteous in you; for God is a Spirit,
and in the Spirit and truth He is known and served, and there His counsel is received.
In the measure of truth in your inward parts,
feel that which never sinned to be near you; then draw near to God in Spirit,
and keep there, and wait and hearken, abiding in that Seed which cannot sin.
In this, wait upon the Holy Spirit and mind His motion continually,
being obedient thereto, that you may come to serve the living and not the dead,
and so be able to say your Redeemer lives,
and that you know Him and have heard His voice.
Then you may say you have learned of Him, and are joined to Him,
so as to be made conformable to Him who lives and sins not.
And His appearance will be your daily salvation and peace,
and well as your growth and increase in God,
and an entrance will be daily ministered thereby into the everlasting kingdom,
which is in Christ Jesus the light and truth and power of God.

But if you go out to any other thing for help
or counsel besides that Spirit which is pure,
just, meek, and lowly,
and which springs up in you to bring forth fruit
to God in that Seed which is pure and clean,
then you go from the fountain of living waters to dig cisterns for yourselves.
In this way you go out into your own works,
and what you bring forth is your own righteousness,
and not that righteousness which is revealed
from above to all generations of God`'s elect.
So you will go through your work with labor and toil,
and when you have brought it forth it will not
satisfy that part in you which hungers after God,
but will only puff up that nature which is selfish,
and exalt that which is already too high to receive life from God.
This righteousness is not accepted by God,
for it is brought forth by works and not by virtue of the divine nature.
But the righteousness which God accepts springs freely within from an eternal Spirit,
and those who enter into it, enter into their rest, and keep the holy Sabbath,
being freely fed and covered by the Lord.

Therefore, if you desire to be born of this heavenly birth,
then cease from flesh and blood,
and from whatever it does for you (within or without) that is defiled,
and wait in that which calls to you and convinces you of sin.
Yes, wait and be faithful,
until you find a life and a desire quickened in you
which can delight in nothing but what is pure,
just and holy, and loathes whatever is contrary, and cannot join to it in thought, word,
nor action.
This is the life of the holy Seed, if ever you feel it move and breathe in you,
and as its spiritual birth grows in the vessel,
it makes it heir of the heavenly treasure, though at first it is weak,
as a child without understanding or strength.
Yes, at first you do not know how it could ever come to have all power and dominion in you,
by reason of the abundance of corruption that has risen above in you,
and the strong bonds of iniquity that rule in your flesh,
which all war against the resurrection of this innocent birth,
and by which the strong man keeps his house with subtlety and
spiritual wickedness against the pure and simple life.
Yet if you will but abide in that which first gave you light, and be obedient thereto,
you will feel it arise and lead you a way you do not know.
And though you may come through great travails and temptations,
and many fiery trials and tribulations, where you are sifted and winnowed,
yet not one grain of that pure seed shall perish or fail in the way,
for the Spirit of light and truth will lead you.
This is the path which has been tried in many generations;
for this is Christ Jesus--the light and salvation of ages,
who has overcome the devil and the world,
and all the power of darkness for all that were sanctified.
And now He is come to do it in you,
that you may also inherit the purchased possession and
sit with Him in heavenly places also.

So then, your work is faith and obedience,
and patience towards Him who is Spirit and light in you;
to Him you must give up your life and your all.
He will confound your corrupt wisdom and give light to
all who are yet under the shadow of death.
He will build up in you the way of peace,
and you shall no more live by your works and natural gifts, but because He lives in you,
you will live also, and your life will be that which is begotten of God and never dies.
This He will do for as many as give themselves
up wholly to the light that leads out of sin.

But you who pray and profess,
and seek and cry for help abroad--not knowing the One who has help in His hands for you,
nor waiting in Him alone,
that in all things you might observe Him--you worship what you do not know.
Though in words you talk of the God who lives,
yet in works you deny Him and give your strength to what is dead and not living.
But tell me, should not every man know his God to live in him,
and go to his own God for life,
according to "`the manifestation of His Spirit given for the profit of all?`"^
footnote:[1 Corinthians 12:7]
And should you not hear and know and learn of Him--not in dead forms,
but in the power of the Spirit of life?
His Word gives life to as many as have an ear open to hear the living Spirit,
and can discern the living from the dead.
But whatever you look to for life and salvation which is not of this Spirit and power,
will kill and devour your strength, for nothing gives life but the Spirit of God.
Only this pure Spirit can feed the hungry soul with the bread of life,
and to this Spirit you must give up all that you have and are.
Yes, you must spend your time and all your strength in hearkening and obeying,
that you may grow in that life which is bread indeed.
But when you give your strength to customs, forms, and carnal rudiments,
to vain pleasures and delights, setting your minds on visible things,
you spend your strength for what is not bread,
and your labor for what does not profit unto life eternal.
Instead, you should wait in that which is pure, that He may open the door of life to you.

Now mind and consider your ways,
you who have looked outward to the mountains to worship and feed yourselves.
You may read of Israel`'s sin in going out from the temple,
in which the Lord had said He would dwell and be sought.
They built altars outside of His temple,
and there they called upon Him but found Him not,
for which He rejected their worship and their temple also.
And where has Christ said He will now be worshipped?
Is it not within?
For Christ has said, "`The true worshippers worship the Father in Spirit and in truth.`"^
footnote:[John 4:24]
Mind this, all you professors of Christianity.
He will not be inquired of in Jerusalem or any outward temple, but in Spirit and truth;
and the body is now the temple, as He has said: "`I will dwell in them and walk in them,
and I will put my law in their inward parts,
and all shall know me from the least to the greatest.`"^
footnote:[2 Corinthians 6:16; Jeremiah 31:33-34; Hebrews 8:11]
The Godhead does not dwell in temples made with hands,
nor in your high places and steepled buildings, but in that which springs from Him.
Can you read this and understand it rightly?
It is in that which springs from Him that the Godhead and power are known.
But the high-minded are too far off it to feel it.

It is the poor and lowly in spirit that are near to the power,
and only he that has become as a little child can understand it,
who is not too great in his own thoughts to hearken to
that Seed which is little and pure in him.
For this Seed springs up by birth, and is the nature of God,
but it is not known in the lofty mind which has divine notions but not nature and life,
nor the sonship which is born of God.
A sanctified life and vessel is God`'s offspring; but he that says he will but does not,
is not born of truth, but of fornication and falsehood.
So then, read your birth and nature and kindred with the light of truth.
It is not the uncircumcised in heart that is the offspring and child of God`'s love,
but rather the pure and clean in heart, mind, and spirit.
And if you desire to be godly you must know this in yourselves,
or else you are without God in the world,
having neither seen Him nor known the one you pretend to worship.
Instead, you are alienated from Him in your minds and in your members,
and in your whole strength, so that you have neither power nor understanding to do well,
being taken captive by a contrary spirit in all your abilities of spirit, soul and body.
Indeed, your wisdom is perverted and your understanding darkened,
having departed from God at the root.

And now this should be your way of return:
to sink down to that gift which is holy and pure in the light,
and give to it your whole man, and all that you are and have.
Consult no more with your wisdom, nor follow your own understanding,
but let that little Seed in you lead you, which is pure and simple,
for to this alone you must bow and bend and confess.
This will be your restoration to God, to give all that you have to the Holy One within,
who, when He has made foolish your cursed wisdom and brought down your high conceit,
and bound the strong man, and tied the colt to the vine,
then He will arise in power (who is meek and holy) to rule in your strengths, gifts,
and wisdom, having purged out the enmity and renewed your abilities.
Thus all will be restored again abundantly; all will be new and clear and able,
by the power of the holy One who will reign and govern therein.
And you shall know the Lord (whose offspring you
are) to be both root and head and all in you,
and you shall no more say, "`I am weak and can do nothing,`" but,
"`I can do all things through Him that gives me strength.`"^
footnote:[Philippians 4:13]
Then the devourer shall no more pervert your strength,
but great shall be the Holy One in your midst.
So you shall no longer sow for the devourer (as you have formerly done),
nor bring forth fruit unto blasting, but your fruits shall arise unto God,
who will receive them with good will,
and your prayers shall not return empty when He has bent you for Himself,
and taken away the accursed thing from amongst you.
And then you will see that all who despise the
day of small things neglect their own mercy,
to follow the teacher of lies.
These do not turn at the Holy One`'s reproof, and therefore worship without power.

And you will know the life and power of redemption, sanctification,
and justification, and the renewing of the Holy Spirit in you,
when your strength is redeemed to God, your wisdom redeemed, your hearts, tongues,
eyes and ears, and all you have redeemed unto God, into that which is holy,
to be guided and exercised in all your conduct,
possessing your vessels in sanctification.
Here the renewing of the Holy Spirit is known,
which sanctifies and justifies through the redemption of both body and mind,
and the reconciliation which is in Christ Jesus.
For Christ is not known to be Lord except by the Holy Spirit, who leads into all truth,
which truth is an inward witness against all who say they are redeemed to God by
Christ Jesus when another lord still rules in them and leads them captive into sin.
In this way, Jesus Christ is denied by them, and suffers in them,
and they remain separated from God and in a nature contrary to Him.
Therefore you must come to that which changes your nature,
and not only your words and forms and teachers.
You must come to Him who begets another seed and kills that which is begotten of
harlotry and lust (which is according to the prince of this world),
so that God may be served in His own Spirit, in His own truth,
and in the nature of His own begetting,
being holy as He is holy in every measure of your growth.
Thus the least of His children may be known to be of Him,
coming out and being separate from the world in soul and in body,
and bearing His image and reproach.

And as many as honestly desire to be heirs of this holy power and kingdom,
patiently wait till you feel something move in you which is of this pure nature;
and having felt it alive in you, rejoice in it with hope and faith, and keep therein,
and be not discouraged because of its littleness in your present sight,
neither seek to judge and measure it thereby,
for you know not what power it has with God, and how precious it is in His sight,
and what it will do for you by His hands in the time of need.
You have not yet proved it, nor can you prove it,
while there remain greater things than this in your thoughts to run to.
The power of holiness and truth in the inward parts is only known in the depths,
when the fire of wrath comes upon all vain hopes and hypocritical confidence,
when all that is without a man is removed far away, when all relations,
friends and acquaintances become farther off than strangers,
and whatever things the creature seeks for comfort turn against him and add to his grief.
Then the power of holiness is known, and truth in heart with God,
and a clean conscience will speak peace;
and none can take this away from you so long as you abide in it.
One who has proved it commends it to you,
who has been stripped of all that he might learn and
know the treasure of life and holiness with God.
Therefore, judge not that which is holier and lower than yourselves,
but let that Seed which is just and holy judge all that has risen above it in you,
which is not of His nature.

The reason why this Seed is so little esteemed by you
is because you are so great in the contrary nature.
So the proud despises the poor, and the rich undervalues him that is better than himself.
This you will find to be true,
if you will measure with that by which God esteems and weighs all flesh, namely,
that which is His own.
So do not judge the most holy, but believe and obey,
for the time for you to judge has not yet come,
until the most holy and just One has become king in you, and you in Him.
Therefore, keep in that which is holy and just, and grow in Him that He may rule in you,
and may arise (through the death of His enemies) to be
greater than the greatest herb in the garden,
greater than the world and the prince of it, which is the devil,
from whom comes all unbelief, false fears and doubting,
and exaltation against the Holy One.
And as these towers fall which are lifted up against the Lord,
so His way will become plain, and truth will take His place in you as King and Lord,
and unbelief will have no place.
And as the pure Life arises, you will find a change in your mind, your nature,
your judgment, and your government,
and you will come to know that the kingdom and power of
the Most High stands in the anointing of the most holy,
and that the kingdom of God is within you, and that the poor is he who inherits it.

So you must not fix your faith upon that which seems great and strong in you,
or that which seems hopeful, or promises great things.
Rather, believe in that which is most holy, true, and righteous in you,
that you may come to the Anointing in your own particular.
It is He who will bring you into the assembly of the
sanctified where the Holy One reigns over all;
for it is He that is sent into the world that lies in wickedness,
to gather them one by one into sanctification,
and therein to present unto God as many as receive Him.

Now, all the world take notice of this:
this is He whom the Father of lights has now sent into you that are in the world.
This is the Holy One, sent of God to call you and give you light, who says of Himself,
"`I am the light of the world.`"^
footnote:[John 8:12]
Hear Him and believe, that you may become children of light and truth;
for this is the glad tidings and gospel of Christ Jesus.
Outward professions and forms would limit the Holy One to themselves and exclude others,
but God`'s gift is free in Christ Jesus, and His offer is to all men;
for He would "`have all men to be saved and come to the knowledge of the truth.`"^
footnote:[1 Timothy 2:4]
He excludes none but those who will not receive His gift, His Son,
the most Holy One who calls you,
and who through the preaching of the gospel has come near to you.
Yes, He is in you with His light (without money or price),
giving you to see the way out of darkness, which nothing else could do for you.
And now, if you receive Him and keep His sayings, and obey His movings,
He will dwell in you and take up His abode,
and you shall know that the Father has sent Him to call
you out of the world into the light of life.
If you deny Him, He will deny you; but if you receive Him the Father will love you,
and power from above will be given to become the sons of God.

Therefore mind that Spirit which calls you out of sin, out of the world,
and gives you light to see the sin and deceit in your own hearts.
Hearken to that which is holy and would turn you from evil,
for this is from the Holy One, the most High within you; believe in Him and follow Him.
Do not believe those who tell you He is not within you, who are "`past feeling`"^
footnote:[Ephesians 4:19]
in themselves and have already rejected Him.
But you who feel Him, abide in Him who is holy within you,
and who witnesses against all unholiness.
If you do not cut yourselves off through disobedience and unbelief,
He will in no way cast you out, but will increase your light through obedience,
and purify your souls and cleanse your vessels,
and work in you mightily by His truth unto salvation.
So you shall see that His working is pure and good,
and is that which no other can do for you.
Yes, this is the Lord your righteousness, though you do not yet know Him as He is.

And if you will receive the Most Holy,
this is your time and the day of your visitation by Him.
His light is now rejected by the builders of this world,
and the wisdom of the wise will not know Him.
No, they will not allow Him to rule over their carnal rudiments,
nor be all in their hearts, nor guide by His light unto salvation.
So He is preached to the outcasts, who are far off and have not sought Him.
These He seeks with His light, and if you do not reject Him He will make you see light,
though you have sat in the region of death, and gross darkness has covered you.
Therefore, hearken to the One that says "`come,`" and feel the Spirit that draws you,
that you may answer His love freely, as it is freely offered.
Know Him by His holiness,
and let His unchangeable witness in you (both day and night)
persuade your hearts that He is the Lord who changes not.
Yes, He that declares unto man his thoughts, the Lord of hosts is His name.
And you who withstand His appearance in Spirit,
and tell people that this is not to preach Christ (though you profess Christ is in you),
tell me, what is Christ in people, if He is not light, and a holy life,
and a faithful witness against the contrary nature in all in whom He lives?
How else may He be known in Spirit, life, and power, if this be denied?
So then, let the mouth of antichrist be stopped,
that the simple may continue on the right and living way,
free from all who will neither enter the kingdom themselves nor permit others,
who have always resisted the Holy Spirit.

[.asterism]
'''

[.blurb]
=== The Fruits of the Freeborn Cleared from Legal Performances, and the Children of Bondage Shown the Nature of their Works.

The children of this world--who have the form but not the power of godliness,
and who have notions of life,
but not the nature and Spirit thereof--judge the children of
light with their dark thoughts and their unfruitful spirit;
and when they see us acting in the life of Christ Jesus,
they then say we are under legal performances,
and that we think to be saved by our works and by our own merit, etc.
But these are greatly mistaken and are not in that Spirit which can
see us or judge the nature of our works or our aim in these things.
Therefore, let all be silent and hear what is now said to you, if you have an ear to hear.
For though you yourselves may be dead, withered branches,
cut off from that tree which is good by nature,
yet it is not so with such as are born again and ingrafted into the good olive tree;
for he that is really born of God knows two different seeds and natures,
which spring up and bring forth fruit from different roots,
according to their different kinds.

Now, the first of these is in bondage, together with its branches,
and it brings forth fruit unto self, from an outward observation or literal command,
or when something within that is carnal or natural sets itself to work.
And thus attempting to work in spiritual things
which are contrary to your life and nature,
you move on with difficulty, and if you attain the outward performance,
then the boaster rises up to glory in what you can do--though you do all for self-ends,
and look to be praised above those who cannot do as you have done.
But you who have not succeeded in the outward performance,
but wearied yourselves therein, and found nothing but bondage,
you turn back to fleshly liberty again,
and judge all others according to what you have found in yourselves,
saying that all good works are from the spirit of bondage,
and from boasting and seeking merit with God.

But you should not judge the children of light according to the flesh;
your measure will not reach that birth.
For he that is born of God is a branch of another root and seed than you know,
which has another nature, inclining to God from which it comes,
even as the first branch inclines to the world from which it comes.
And as the natural man does evil naturally with delight,
his root and life being of this kind,
so the spiritual man (in his measure) does good naturally after his root and life.
Yes, it is his pleasure and joy to bring forth fruit from the root that is good by nature,
even as it is the delight of the other branch to bring
forth fruit from the root that is evil by nature.
For as is the heavenly One, so are those who are heavenly,
and it is no bondage for the heavenly branch to bear heavenly fruits;
but to the earthly man this is bondage, being a striving against his nature.
Therefore Christ says, "`make the tree either good and its fruits good,
or the tree evil and its fruits evil.`"^
footnote:[Matthew 12:33]
Thus good trees, evil trees, and fruitless trees are known to be of differing natures,
bearing different fruits.

So then, it is but your own darkness that thinks this way,
and with evil thoughts you judge amiss.
Will you say of those who are really planted into the living Vine that their
fruits (which freely spring from here) are legal and are bondage,
and that we think to be saved by our works, and by our own righteousness, etc.? No,
these are the fruits of those who are saved already,
and who have ceased from their own works and received righteousness from God.
Indeed, the works of these are no more legal, but spiritual,
no more from bondage but free, and he that is in Christ is fruitful in good works,
and free therein by birth.
And he that abides in Christ sins not, nor is his seed of the evil one.

If you could understand this,
you would not condemn the fruits of the living with the
fruits of those who are dead while they live,
whose fruits are withered.
These are broken off from the One that is good by
nature and planted into that which is wild by nature.
Thus you cannot judge the spiritual man, or his fruits, his freedom, his offspring,
or his end; but he can judge all fruitless trees, though he himself is judged by no man.
I know it is hard for you to do good who are accustomed to do evil,
even as for the leopard to change his spots;
but it is otherwise with those who are changed already, born of the light,
and heirs by birth and by nature to the everlasting righteousness and truth.
For such as these it is hard to do evil, being against their nature, seed, and sonship,
which are in God.
And though you cannot believe this, yet he that is born of faith can and does;
for the least child of God can read this in their measure,
who know the difference between the old Adam and the new.
And even as in the first nature all are in sin and bondage,
so in the second are all made righteous and free unto God`'s work;
and in the second the new creation is known wherein righteousness dwells,
as God has said, "`I will dwell in them and walk in them.`"^
footnote:[1 Corinthians 6:16]

Will you call this self-righteousness, where all things are of God,
and all things are made new?
Are these legal works and a yoke of bondage?
If any man be in Christ, all things are of God,
and it is God that works in us of His good pleasure both to will and to do.
No, this is not the spirit of bondage,
but rather the good will and pleasure which God freely works in us.
And reproaching this, you reproach what God works by the hearing of faith,
which is the same righteousness that was wrought in Abraham,
which was also in God before Abraham was,
and is a free gift to all who (by Abraham`'s faith) come
out of the world unto Him who is not of the world.
But you who abide in the world do not inherit this righteousness,
for you remain in self and are seeking yourselves in all that you do for God and for men.
"`How can you believe?`"
says Christ, "`who look for rewards from men,`"^
footnote:[John 5:44]
and are not in that Spirit which works freely?
Yes, you look for praise, honor, merit, and respect of persons, both teachers and people,
in that nature which is outside the faith of Jesus Christ.
For He went from place to place doing good freely and preaching freely,
and so do all who are born of true freedom.
You speak of His life, but know it not by birth and virtue,
which is naturally good even as the first and fallen man is naturally evil.

Now, the bondage is found in that which works against the pure nature,
and not in that which is freeborn;
and the law is upon the transgressor and upon all who have
degenerated into that nature which is carnal and sensual.
If this carnal man does anything as unto God,
it is from something that is laid upon him from without, and not in the Spirit;
and _this_ is legal and under bondage, for it is not done by the free Spirit,
who by nature does the things contained in the law.

And truly, little would the natural man either do or know,
if there were not an outward law or letter, or a heaven and hell to set him upon working.
Here is the bondage and the fear that has torment.
But it is not so with the spiritual seed,
who are begotten and born of God in Christ Jesus,
in whom they freely receive like a branch from its root.
And what the root sends forth through these branches are the fruits of His Spirit,
against which there is no law.
This is not legal, but spiritual and free, and such are a law unto themselves;
for there is no law against the Seed,
but the law was added upon the transgressor (because of sin) until the Seed should come;
and wherever the Seed is born and rules,
there the creature is not under the law or letter, or under traditions or bondage,
but is led by the Spirit, and born of that nature which was before transgression.
And by this,
the fruits of righteousness are brought to light by the working of the Holy Spirit,
who works both the will and the deed from His own good pleasure,
and with the same good will and pleasure the fruit is
brought forth without bondage or constraint.

And in whosoever the bonds of iniquity are broken, there the world has ended,
all things have become new, and all is of God.
There self-righteousness does not dwell, nor the spirit of bondage,
but there is a new creature in Christ Jesus (not
in self) which is created unto good works.
Here the heavens are new, and the earth is new,
and righteousness dwells in Christ Jesus who is revealed from God in Spirit and power,
to which the law and the prophets bear witness,
having foretold what glory and freedom should be
revealed in the latter days at the Seed`'s appearing.

But before you can judge concerning this freedom,
or the nature of the works that spring from it,
or inherit the power that brings forth this righteousness,
you must acknowledge the judgment of Him that condemns the man of sin in you,
and receive Him for your lawgiver.
This will break you off from the world, and cause you to deny its forms and images,
and bring you from under its power.

Therefore, take heed to yourselves,
all you that name the name of the Lord and call Him master.
Depart from iniquity and obey righteousness; this is His work, if you are His servants.
He has called you to holiness, even as He is holy, and so you must turn from the world,
and repent of the works of the prince of the world,
denying him and his works both openly and in secret.
If you will serve the Holy One you must bear His mark
and open your heart to Him and your mouth for Him,
even as confidently as the servants of sin do the same for it.
In this way your light will shine against the darkness of this
world in the face of a perverse and crooked generation,
and it will appear to all men that the ways of the Lord and the world are not one,
nor are their servants one, nor their words one, nor their garments one,
nor their table one.
In all things you must bear His image and glory above His adversary,
that it may appear to whose family you belong,
and what the work of your Lord is in the world.

And herein all people may see themselves, as in a mirror,
whether they be for God in this His day, or whether they be against Him.
There are but two masters of whom Christ speaks, and none can serve them both.
The one is hated and the other is served; so now, who has hired you?
Who do you serve, and who do you hate?
Is it the world you serve?
then you hate Christ.
Is it Christ?
then you deny the world.
These are plain things,
and you may see clearly as you go your way whose
business you are about and whose hand you strengthen.
If you commit sin and contend for it,
then you war against Him who was made manifest to destroy sin.
And if you say sin must live in you while you live on the earth,
then you believe the devil must have a place, a power,
and a kingdom in you as long as you live.
But if you believe to overcome sin,
then you wait for the kingdom of God (which consists in righteousness),
seek it daily with your whole heart, and believe to see it.

Now it is not words which take the kingdom,
but the power of faith against the evil one.
Neither is it religious forms and professions or
any outward thing that can vanquish the devil,
for he is a spirit, and must be resisted by a spiritual power.
Indeed the weapons which cast down his seat in man are spiritual and mighty through God.
But alas, many are led from form to form which deny the power of God in them,
but obey the power of sin in them;
not knowing the power which lays the axe to the root of
the evil tree from which all evil springs.
But you have not yet come to labor in the vineyard of
God till you be set to work against sin,
and to pluck up and cut down (with His spiritual light and power)
every evil thing that offends in the kingdom of God,
which kingdom is within you.
For that which offends is within you, and that which is offended is within,
and that which is lost is within, and there it must be sought.
Yes, the Pearl, the Seed, the Word, the law of the Spirit of life,
and the covenant is within,
but these are not seen or believed till the house of God is swept,
and the fruits of darkness are denied, and the light of Christ is turned to,
and the Righteous One is obeyed.
But you will see the unrighteous one, and the power that works against him,
when the ground of darkness is removed by the working of faith.

Now, as many as are called to this work, and entered into it in truth and faith,
must not be idle, but must obey the Spirit of life until the house be cleansed,
the unclean thing cast out, and the Pure One exalted.
Then you will find your holy rest within you, and your God near to you,
and your souls dwelling at ease with God in your own habitation, whose temples you are.
And this is not self-works, nor self-will, but pure faith and obedience to the Seed,
or living Word of God, which wars in you against the world and every selfish,
fleshly lust and delight.
This is the Seed of the holy covenant, which Seed is Christ, the Holy and Just One,
if you can receive it.
This is He that makes you clean and keeps you so, as you obey and walk in Him.
From His Spirit you must receive your law,
which Spirit gives to you His life to inherit here on earth.
And if you walk in the Spirit you shall not live according to the flesh.

Then the common objection (which the spirit of this world
makes against the holy life and kingdom) is easily answered,
wherein they say, "`If it is possible to live without sin,
then there is no need for a Savior.`"
For those who have truly learned this life and knowledge find
that the One who cleanses the house must also keep it clean;
and He that is the death of sin is also the life of righteousness;
and the same light and fear of God which leads to the putting off of the old
man (with his affections and deeds) leads also to put on the new man,
who is renewed after the image of Him that created him,
where Christ is all in life and guidance, and the good Man keeps the house,
not the strong man.
How can any say he needs no savior when he can do nothing without Him,
whose righteous life is both his food and clothing,
and Christ`'s light is the daily armor against evil in every thought, word, and work?

Therefore, all you who profess Jesus Christ to be your Lord and master in words,
let it be also in truth and righteousness,
so that in whatever place or employment you are found,
you will be chiefly about His work and not your own.
Now, His work is manifest whenever He appears; for it is always against sin,
to destroy the works of the devil in this world,
so that the kingdoms of this world may become the kingdoms of Christ Jesus,
and that the most Holy One may rule and bring forth His fruits therein.
Now His servants are known by this,
that they stand for the kingdom of Christ in this world,
and against all the works of the devil.
And the servants of the devil are known by the contrary, by being about his work,
which is to keep sin in this world as long as people live,
for this is the strength of his kingdom.
If you take away sin, you take away his kingdom here, and his power here,
and his place here, for where he is resisted he flees.
But where he is received he sets up his throne and takes pleasure in his servants,
and they take pleasure in his work, which is to increase deception and vanity in them,
and to fill their hearts with every lust.
Thus they are carried away after every desire till they
have no delight in anything that is contrary,
nor can believe that any can receive power in the Spirit of Christ against the devil,
or know such a redemption as to overcome sin in this world.
And here an agreement is made with death,
and a covenant is established with unrighteousness.

All who are of this mind and belief,
you are not yet servants of Christ Jesus the righteous, nor have you received His faith,
which is pure even as He is pure, and which believes unto righteousness and victory,
and not unto sin.
This is the faith which overcomes the world and the prince of it,
and resists the devil steadfast in the faith, in hope of victory in the end.
These have their hearts turned and their faces set towards holiness,
and are set on their journey out of the world.
Their mind is fixed on Christ`'s holy and pure light in all their travails, tribulations,
and temptations, which works more hope, and more strength daily,
and every trial that they meet with in the way gives experience and
renewed strength against their adversary the devil,
while they keep close to Christ in faith and love.
And though they feel the devil in the sensual part to be strong and powerful,
and past their present strength, yet they yield him not the kingdom,
but sink down into the faith and hope and patience of Christ Jesus,
waiting for the resurrection of that life which never sinned,
and for the appearance of Christ without sin to save them from the power of
death which wars in their members to bring forth sin in this world.
And this is their true service and faithfulness:
to wait for the kingdom of God within them, and the righteousness thereof,
and the coming of their Lord, with their minds girded up with holiness,
and their hearts steadfast, not to consent to the least work of the devil,
even if it would gain the whole world for the sensual reason and wisdom.

And if these are overtaken with a fault, it is not willingly,
but as a servant of Christ they stand against their own sin as far as they then see it.
And knowing sin to be a work of the wrong master, they abhor it and themselves for it,
and deny it, and will never plead for it or seek to hide it, but rather confess it,
and cannot have peace until it is cleansed out.
These are the little children who have an advocate with the Father,
to whom sin is like death, and they dare not speak a word for it, but only against it,
both in themselves and in others.
And these appear against sin openly and confess all (with
their hearts and their words) to Him who is holy.

But what a difference is there between one of these--who when
they either see or are told of their offense against the Lord are
broken into tears or sorrow before the least reproof,
condemning themselves openly for it, and condemning it in themselves--and you,
who when you are reproved for sin (which is both open and known) set
yourselves with all your strength and wisdom to excuse it,
and (like the devil) employ the Scriptures to strengthen yourselves against just reproof.
Yes, with hearts full of envy and mouths full of reproach, you stand up,
seeking to ensnare those who reprove you in love to Christ`'s kingdom and to your souls.
You scoff at those who seek to recover you out from the works of Satan,
those who desire that his kingdom might fall in you,
leaving him fewer subjects in his power;
and that you be added unto the kingdom of Christ by being brought under His commands,
through denying your old master, and confessing and condemning his evil works.
For truly,
there must be a denying of the devil and his works before Christ will receive you.

[.asterism]
'''

[.blurb]
=== Christ Jesus Known to be King in His Temples, through the Power of the Holy Spirit and the Sword of the Spirit, Lifted Up Against the Man of Sin in True Judgment.

You who look for the kingdom of Christ Jesus,
know that it stands not in observations, words and forms,
but in the power of the Holy Spirit, in judgment, in truth, and in righteousness.
If you desire to know His appearance unto salvation,
wait for it in that Spirit and power which is holy, and which judges and condemns sin.
For to know His spiritual power within as a witness against
all sin (by the breath of His mouth and the sword of His
Spirit)--this is His kingdom with men (if you can receive it).
Herein men find power to judge all contrary spirits within and without,
and all contrary actions;
but whatever opposes and denies His kingdom in His temples is antichrist.

For Christ`'s temple is the new creation of holy men and women in
whom He speaks and dwells and walks (as the Scriptures testify),
and in whom He judges the prince of this world
and all his works in the children of darkness.
And in His own temples Christ shows forth His nature and
virtue as a witness against the devil and all his works.
Whoever would hinder this is antichrist,
who sits in the temple of Christ to resist the Holy One and to reject
the righteous judgments of Christ against sin in His temple.
Such as these cry out "`Do not judge,`" whenever Truth speaks,
and "`You must not judge lest you be judged`" when the
Spirit of Christ testifies against sin in true judgment.
So through deceit these would turn Christ`'s words against His work,
who said "`I will redeem Zion with judgment.`"^
footnote:[Isaiah 1:27; See also Isaiah 4:4]
For when Christ said, "`Judge not lest you be judged,`"^
footnote:[Matthew 7:1]
He did not speak these words to save sin from judgment,
nor to stop the mouth of truth and righteousness,
for He then would have contradicted Himself where He
commands them to "`judge with righteous judgment.`"^
footnote:[John 7:24]
Indeed, Christ has been manifest to destroy and not to save sin,
in whomsoever He is manifest, and for this end He lives in His people.

Therefore you professors of Christ in words and forms, seek His kingdom in you,
and take heed that your forms do not withstand His powerful appearance in Spirit.
His kingly authority stands in His heavenly, holy nature and virtue in Spirit,
and not in perishing rudiments and outward shadows.
Read in Scripture how often antichrist has deceived people by
causing outward forms to withstand the spiritual power,
and so has kept people in words without life, opposing Christ in His kingdom.
Therefore, in the first place, seek to know His spiritual nature and virtue,
which has power against sin, both in word and in deed.
Here is Christ`'s kingdom, here is His glory, and here He reigns.
His kingdom is spiritual and holy, and it is within, where His testimonies, laws,
and judgments are known.

And you who are talking of Christ`'s appearance, where do you think He will rule,
if not in the heart (the chief place in man), there to judge, govern,
speak and give out His law?
Will you allow the evil one to utter his voice openly in man, in swearing, lying,
cursed speaking, and every evil work,
and yet Christ must be silent and dumb in His vessels when he sees it?
Is this not Christ`'s privilege in His redeemed ones,
even as the prince of this world has power in his captives?
Indeed, this is the reasonable service of His chosen vessels:
to give up their bodies that He may speak and act and show forth His virtue
and life and power therein against the spirit of the world in his vessels.
And were it not for the words of God spoken by them,
the holy men of God would never have suffered or been hated; but Christ has said,
"`It is not you that speaks but the Spirit of your Father that speaks in you.`"^
footnote:[Matthew 10:20]
This is the voice which the world does not know, and so seeks to stop,
saying it is not the Lord;
but such as these know not that justice and judgment are the
habitation of His throne in the hearts and mouths of His people.

What?
Must the Spirit of truth refrain from judging deceit and falsehood where He dwells?
Must not that which is holy judge the unclean?
Must not that which is lowly judge the proud, and that which is chaste judge all lust?
Must not "`he that is spiritual judge all things?`"^
footnote:[1 Corinthians 2:15]
Must not "`the saints judge the world?`"^
footnote:[1 Corinthians 6:2]
What sort of nation would you have this to be,
you who would root out judgment and yet profess Christ within you?
Is Christ truly in a people where there is no judgment against sin, pride, excess, lying,
swearing, false ways and false worships?
Would you have all sin to pass openly without reproof?
Has the land wholly become like Sodom?
Consider the words of the men of Sodom to Lot in this case:
"`This one came to sojourn here, and he keeps acting as a judge.`"^
footnote:[Genesis 19:9]
For this reason Lot`'s "`righteous soul was tormented from day
to day by seeing and hearing their lawless deeds.`"^
footnote:[2 Peter 2:8]
Would you have sin go on openly in the streets without reproof and shame?
Where then is the Holy One?
In whom does He dwell who is of "`purer eyes than to behold iniquity?`"^
footnote:[Habakkuk 1:13]
Is Christ a king?
Is He a judge?
Is He pure and clean in heart?
Does He live?
Can He see sin and be silent where He has a mouth by which to speak?
Consider His walking formerly in His servants, and what He did and spoke in them,
and against what.
And is He not still a God of judgment near at hand against His adversary,
(though those who do not know His voice put Him far off)?

So you who say you are for Christ and His kingdom,
consider whose kingdom sin is in, and whose work it is to defend it from judgment,
and distort the Scriptures to contend for it.
This is most surely to "`justify the wicked and condemn the righteous,
both of which are an abomination to the Lord.`"^
footnote:[Proverbs 17:15]
Therefore, if you love the appearance of Christ Jesus, you must not love sin,
but in that Seed which cannot sin, you must feel Him who suffers because of sin,
and yet is without sin and is against sin.
And if you come unto Him whose appearance is holy, just, and true,
and therein join to Him, you will love that which condemns sin.
Then you are truly for Christ, when you can feel and suffer with Him,
and then you will see that nothing is offended when sin is judged,
except he that is guilty thereof.

[.asterism]
'''

[.blurb]
=== Grace Received, and Grace Rejected.

The grace of God is that which brings salvation near to man,
giving him a sight of truth within himself;
for God desires that all men come to the knowledge of truth that they might be saved.
All men are naturally darkness, being "`without God in the world;`"^
footnote:[Ephesians 2:12]
thus the grace of God is offered to all without respect of persons.
Now this grace is one in every man and neither spares the evil
nor denies the good in any out of respect to either person,
wisdom, strength or the riches of this world.
It has respect only to the Spirit of truth in all, and man`'s obedience thereto,
seeking to teach and lead all to salvation, and to the true worship of God in Spirit,
to eternal life, and to the growth of the holy Seed in man,
quickening the soul which has suffered from sin.
This it does by condemning sin in every motion, and also by ministering comforts,
promises,
and power in the Spirit in such a way that the soul may
arise above the power of the son of wickedness.
Yes, it is grace that ministers light and understanding in
the inward part to the soul that hates sin,
daily opening (through the obedience of truth)
that eye which the god of this world has blinded,
and purifying the soul by putting off the body of corruption.
And it is also grace that blinds the eye of him
who says he sees but knows not the way of sin,
and also ministers the law upon him.

This is the ministration of free grace to every soul that receives it,
working powerfully in all who abide in it, through the Spirit of Christ Jesus.
And as the Scriptures say, this "`grace has appeared to all men;`"^
footnote:[Titus 2:11]
yes, and daily appears in all who truly wait in Spirit for its appearance,
giving to these a sight of truth in themselves,
testifying with or against every motion of the
heart according as it stands in the sight of God,
whether it be good or evil.
In this way, "`their consciences bear witness,
and their thoughts accuse or else excuse them in the day when
God will judge the secrets of men by Jesus Christ.`"^
footnote:[Romans 2:15-16]
So then,
it is not a fault in the grace why some are not saved by it from sin and condemnation;
but grace being rejected becomes man`'s condemnation.
The same grace that saves the one who receives it in faith and
obedience also condemns the one that rejects it in disobedience.
This is the grace of God that changes not, and which appears to all men,
but only reigns unto salvation through righteousness
where it is believed to be sufficient and obeyed.

So then, that which is of God in man is His grace,
which ministers spiritual light to the soul in the midst of darkness,
and life to that which is dead in sin.
It leads man through the vale of death up to God
from where it came and to whom it belongs.
And the light of this grace is judgment and discerning
in everyone that receives and is led by it in judgment.
But the same is condemnation to such as turn grace into a license for immorality,
denying the life thereof and the truth it leads into.
These cannot be saved through it.
But he that receives it and joins to it in Spirit becomes one with it,
and by his daily sinking into its counsel, it grows in him and he in it,
until it becomes a habitation and covering for him against all evil.
So he becomes gracious in words and works, daily receiving of Christ`'s fullness,
even grace for grace.

Now he that has received of this grace and is faithful
therein must not minister from it to strengthen the
transgressor (who loves his sin and so is under the law),
nor cast his pearls before swine.
For grace ministers judgment to the wicked,
that thereby they may know their condemnation by the light of truth,
and no longer deny grace its reign.

But to such as are heavy laden and weary of sin,
these he is to encourage against the sin and temptation (which
all that turn from the devil must expect to meet with).
And he that receives the teaching of grace comes therein to the leading of the Spirit,
and so becomes free from sin, and is no more under the law but under grace.
But the law has power over all that walk after the flesh,
and every appearance of grace is a witness against them,
by declaring them to be under the law of sin and death,
and not in covenant with the One that appears
against sin in the power of grace and truth,
who is Jesus Christ the Lord.
