[#appendix-bio]
== Appendix: A Brief Biography of James Nayler

[.chapter-subtitle--blurb]
Relating His Early Piety and Eminence in the Society of Friends,
His Tragic Fall Evinced in the Bristol Incident,
His Open Acknowledgement of Error and Sincere Repentance,
and His Subsequent Restoration to Fellowship and Usefulness in the Body of Christ.

[.offset]
__Chiefly Compiled from: The History of the Rise, Increase,
and Progress of the Christian People Called Quakers--by William Sewel;
The Life of James Nayler--by Joseph Bevan Gurney; and The Memoirs of John Whiting.__

[.small-break]
'''

James Nayler was born of honest parents, in the parish of Ardesley,
near Wakefield in Yorkshire, about the year 1618.
His father was a husbandman of good repute,
having a competent estate to live on for the country in which he dwelt.
James was educated in English to some degree,
and is acknowledged (even by his enemies) to have been an eloquent speaker,
though this skill was probably not much more than a natural eloquence,
improved by the limited learning which a husbandman
might be able to provide for his son in that day.

There is very little account of James Nayler before he became a Friend,
but it appears that he was married about 1640, and then removed to Wakefield.
The civil war breaking out the following year,
he became a soldier in the army of Fairfax,
and afterwards a quarter-master under Major General Lambert,
serving in the army a total of eight or nine years,
before being disabled in Scotland by sickness and returning home in 1649.
During all this time, his religious profession was among the Independents.

In the year 1651,
George Fox (having now fully entered upon his public ministry) came to Wakefield,
where James Nayler appears to have heartily consented
to the doctrines which he heard Fox proclaim.
Fox`'s journal informs us that at this time,
"`James Nayler and Thomas Goodyear came to me, and were both convinced,
and received the truth.`"

Nayler appears to have been a person of a tender conscience from his youth,
seeking to keep himself in a posture of attentiveness to the Lord.
In the year following his convincement,
he believed himself bound in religious duty to leave his family,
and to travel in the Lord`'s service according as his way would, from time to time,
be made known to him.
He is said to have received this commission while following behind his plow in the field,
meditating upon the things of God.
He then heard a voice, bidding him go out from his kindred and from his father`'s house,
with a promise that the Lord would be with him.
He exceedingly rejoiced to hear the voice of the Lord,
whom he had professed from a child, and had endeavored to serve,
but after making some initial preparation for his journey,
he did not readily give up to go, but was disobedient to the voice,
for which he said he felt the wrath of God upon him,
and even thought himself in danger of losing his life.
At length, going a little way from home with a friend,
not then thinking of a long journey (nor having provided for one),
he was commanded to go into the west.
He knew not the purpose of this mission,
but upon his arrival it was given him what to declare; and so he continued,
not knowing one day what he was to do the next.

It is not clear whether this journey was to the west of England,
or only westward of his habitation, Wakefield.
The latter is most probable,
for in the year 1652 we find him suffering much personal abuse at Walney Island,
in Lancashire, and disputing with priests in Westmoreland.
In the Eleventh month of the same year,
Nayler was indicted at the quarter sessions at Appleby for what was
termed "`blasphemy;`" that is (according to his indictment),
for having said that "`Christ was in him,`" and that "`there was but one Word of God.`"
The same year that Nayler was released from Appleby jail, if not during his confinement,
he wrote a paper, entitled, __Truth Cleared from Scandal,
Being James Nayler`'s Answer and Declaration Respecting
Some Things That Were Charged Upon Him.__
And as this document contains James Nayler`'s belief concerning Christ (which,
a few years after, became a point of much controversy),
the following excerpt is thought worthy of notice.

[.content-signed-section]
Concerning Jesus Christ: +++[+++says Nayler]
He is the eternal Word of God, by whom all things were made and are upheld,
who was before all time, but was manifested in time for the recovery of lost man.
This Word became flesh, and dwelt among the saints, who is the same yesterday, and today,
and forever; who did and does dwell in the saints; who suffered and rose again,
and ascended into heaven, and is set on the right hand of God.
To Him all power is given, in heaven and in earth.
And though He fills all places, and is the light of the world,
yet He is known to none but those who receive and follow Him.
These He leads up to God, out of all the ways, works, and worships of the world,
by His pure light in them, whereby He reveals the man of sin,
and by His power casts him out,
and so prepares the bodies of the saints as a fit temple for the pure God to dwell in,
with whom dwells no unclean thing.
Thus He reconciles God and man, and renews the image of God in purity and holiness;
and hereby the image of Satan (which is all sin and uncleanness) is defaced.
And none can witness redemption further than Christ is
thus revealed in them to set them free from sin;
which Christ I witness to be revealed in me in measure (Gal.
1:16. 1 Cor. 8:5. Col. 1:27).

After the termination of his confinement,
Nayler continued traveling in the service of the gospel in the north of England.
For several years, he was an eminent member of the Society of Friends,
acquitting himself well, both in word and writing,
so that many came to receive the Truth by his ministry.
He was sound in doctrine, wise in deportment,
and known by all to be a man of great discernment; and many,
even among those who were not called Quakers,
were made to confess that he preached as one having authority, and not as the scribes,
"`in demonstration of the Spirit and of power.`"^
footnote:[1 Corinthians 2:4]
The following anecdote is indicative of the ministry of Nayler at this time.
It is taken from the journal of James Gough,
and relates an event that was influential in the
convincement of the honorable minister and elder,
James Wilson.

[quote]
____
In +++[+++James Wilson`'s] young years,
having been educated in the established religion or church of England (so called),
he had conceived a very contemptible opinion of
the people called Quakers and their principles,
and at a public house falling into company with some others of like sentiments,
this people became the subject of their discourse.
As they were expressing their sentiments of contempt and dislike of them pretty freely,
a person of some note, who had been an officer under Oliver Cromwell, came into the room,
and overhearing their discourse, observed to them in substance:
"`That he apprehended their prejudice towards this
people arose from their lack of knowing them;
for my part, he continued, I entertain very different sentiments of them.`"
And perceiving them struck with admiration to hear him,
whom they looked upon as a man of sense as well as consequence,
express himself after this manner, he proceeded to the following purpose:
"`You seem to wonder that I express a favorable opinion of the Quakers;
I will inform you the reason.

After the battle of Dunbar, as I was riding in Scotland at the head of my troop,
I observed at some distance from the road, a crowd of people,
and one higher than the rest.
Upon seeing this I sent one of my men to see and bring
me word what was the meaning of this gathering;
and seeing him ride up and stay there, without returning according to my order,
I sent a second, who stayed in like manner; and then I determined to go myself.
When I came there, I found it was James Nayler preaching to the people;
and with such power and reaching energy, as I had not till then been witness of.
I could not help staying a little, although I was afraid to stay;
for I was made a Quaker, being forced to tremble at the sight of myself.
I was struck with more terror by the preaching of James Nayler,
than I was at the battle of Dunbar,
when we had nothing else to expect but to fall a prey to the swords of our enemies,
without being able to help ourselves.
I clearly saw that the cross must be submitted to, so I dared stay no longer,
but got off, and carried condemnation for it in my own breast.
The people there, in the clear and powerful opening of their states,
cried out against themselves, imploring mercy, a thorough change,
and the whole work of salvation to be effected in them.
Ever since I have thought myself obliged to acknowledge on their behalf,
as I have now done.`"
____

This, James Wilson said,
proved the first step towards his convincement of our principles,
inclining him to go to our meetings, which, before he had an aversion to the thoughts of,
from the prejudice above hinted.
In those days the meetings of friends were more eminently favored with divine power,
as they lived more devoted to Christ;
and consequently more abounding with his love flowing in their hearts.

We have another short account of Nayler,
taken from the journal of Thomas Ellwood, who,
before he became a member of the society of Friends,
had met with him while visiting Isaac Penington`'s home at Chalfont in Buckinghamshire.
Ellwood writes:

[quote]
____
After supper, the evenings being long,
the servants of the family (who were Quakers) were called in,
and we all sat down in silence.
We had not sat long before Edward Burrough began to speak among us.
And although he spoke not long, yet what he said did touch, as I suppose,
my father`'s religious nerve, as the phrase goes.
For my father having been from his youth a professor of religion (though not joined
in close communion with any one sort) and valuing himself upon the knowledge he
esteemed himself to have of the various notions of each profession,
thought he had now a fair opportunity to display his knowledge,
and thereupon began to make objections against what had been delivered.
The subject of Burrough`'s discourse was the universal
free grace of God extended to all mankind;
to which my father opposed in support of the Calvinistic tenet
of particular and personal predestination.
But in his defense of this indefensible notion,
he found himself more at a loss than he expected.
Edward Burrough said not much to him upon it, though what he said was close and cogent.
But James Nayler interposing,
handled the subject with so much perspicuity and clear demonstration,
that his reasoning seemed to be irresistible; and so I suppose my father found it,
which made him willing to drop the discourse.
As for Edward Burrough, he was a brisk young man of a ready tongue, and might have been,
for aught I then knew, a scholar, which made me less to admire his way of reasoning.
But what dropped from James Nayler had the greater force upon me,
because he looked but like a plain simple country-man,
having the appearance of a husbandman or a shepherd.
____

Towards the latter end of the year 1654, or the beginning of 1655,
James Nayler came to London,
and found there a meeting of Friends which had already been gathered
through the service of Edward Burrough and Francis Howgill.
There he preached in such an eminent manner that many admired
his great gift and began to esteem him much above his brethren,
which, as it brought him no benefit,
so it gave occasion for some disparity in the society.
This continued to such a degree,
that some forward and inconsiderate women (of whom Martha Simmons was
the chief) assumed the boldness to openly dispute with Francis
Howgill and Edward Burrough during their preaching,
and thus to disturb the meetings:^
footnote:[These women`'s practice we may suppose to be somewhat
like that which gave occasion for the apostle Paul to say,
"`Let your women keep silence in the churches,
for it is not permitted unto them to speak.`" 1 Cor. 14:34.
This prohibition of "`speaking,`" must refer to voluntary discourse,
by way of reasoning or disputing,
and not such speaking as springs from the leading of the Spirit,
or from a true concern to prophesy;
for the apostle in the same epistle has defined
prophesy to be speaking unto men
"`for edification, exhortation, and comfort.`" chap. 14:3;
and has also (in Chap. 11) made express mention of women`'s praying and
prophesying together with the men.--William Sewel]
whereupon these two men, who were truly excellent ministers, did not fail,
according to their duty, to reprove this indiscretion.
But these women were so disgusted,
that Martha and another woman went and complained to James Nayler,
seeking to incense him against Francis Howgill and Edward Burrough;
but this did not succeed,
for Nayler showed himself afraid to pass judgment upon his brethren.
Hereupon Martha fell into a passion, and in a kind of moaning or weeping,
she bitterly cried out with a mournful shrill, saying, "`I looked for judgment,
but behold oppression; for righteousness, but behold a cry!`"^
footnote:[Isaiah 5:7]
Thus she continued to cry aloud in a passionate, lamenting manner,
which so entered and pierced James Nayler,
that it brought him to great sorrow and sadness,
and left him in a dejected and disconsolate spirit.
Fear and doubting then entered him, so that he came to be clouded in his understanding,
bewildered, and at a loss in his discernment.
The piercing lamentations of this woman are thought to have
had a great share in the overturning of his judgment;
and regrettably he became not only the dupe of her (and her associates) violent grief,
but was then led further aside by their flattery.
Thus, by giving ear to the fawning praise of a few whimsical
people (which he ought to have abhorred and reproved),
he found himself increasingly estranged from the
leading members of the Society of Friends,
who now could not unite with his conduct.
But his sorrowful fall ought to stand as a warning to all,
even to those that are endued with great gifts, that they do not presume to be exalted,
lest they also fall.
And may all endeavor to continue in true humility,
in which alone a Christian can be kept safe.

Hannah Stranger, whom I +++[+++William Sewel]
know very well, and have reason to believe to be a woman of high imaginations,
at this time wrote several very extravagant letters to James Nayler;
calling him the everlasting Son of Righteousness, Prince of Peace,
the only begotten Son of God, the fairest of ten thousands, etc.
In the letters of Jane Woodcock, John Stranger, and some others,
were expressions of similar extravagance; and the said Hannah Stranger, Martha Simmons,
and Dorcas Erbury, arrived at such a height in their folly,
that they even kneeled before Nayler in the prison at Exeter and kissed his feet.

Near this time, George Fox, being recently released from Launceston Jail,
came to Exeter prison and attempted to speak to Nayler,
whom he acknowledges in his journal to have "`run out into imaginations.`"
At the time of this encounter, Nayler appears to have slighted Fox`'s advice,
and yet he offered him an affectionate salutation, which Fox in turn rejected, saying,
that since Nayler had turned against the power of God,
he would not receive his show of kindness.

Being now thoroughly beguiled, Nayler grew yet more exorbitant.
Upon being released from that prison, he rode to Bristol in the beginning of November,
attended by his aforementioned flattering companions.
Passing through the suburbs of Bristol, one Thomas Woodcock went bareheaded before him,^
footnote:[i.e. without his hat,
a gesture used by Friends only when addressing the Lord in prayer.--Editor]
while one of the women led his horse.
Dorcas, Martha, and Hannah, spread their scarfs and handkerchiefs before him,
and the company sang, "`Holy, holy, holy, is the Lord God of hosts,
Hosannah in the highest: holy, holy, holy, is the Lord God of Israel.`"
Thus these mad people carried on,
while they walked through the mire and dirt until they came into Bristol,
where they were examined by the magistrates and committed to prison.
Not long after, Nayler was carried to London to be examined by the parliament,
and how it went there may be seen in the printed trial
which the parliament was pleased to publish.^
footnote:[But the extravagance of the sentence which parliament passed upon him,
gives great reason to suspect that this published account was far from impartial,
and that it was chiefly published to justify their cruelty.
According to John Whiting,
some of Nayler`'s answers before parliament were innocent enough, some were not clear,
and some were aggravated by his adversaries; some accusations he denied, some he owned;
they reported the worst, and more than was true in some things,
adding and diminishing as they saw fit.
Much is lacking in the printed report of what he spoke to the committee.
But they wrested and perverted his words where they could,
endeavoring to draw out words to ensnare him, and to take away his life.
And to further manifest their confusion,
they sought to make him kneel when he was before them, and to put off his hat to them,
though a part of the charge against him was that some had kneeled to him.--William Sewel]
I believe that James Nayler was clouded in his
understanding throughout this entire affair;
but howsoever grievous was his fall, yet it pleased God, in His infinite mercy,
to raise him up again,
and to bring him to such a sincere repentance (as we may see in what follows),
that he abhorred not only this whole business,
but also manifested his heavy sorrow in heart-rending expressions,
which were published and will be shown in their proper place.

What has been said of the odd doings in Exeter prison,
and of his riding into Bristol, was not denied by him,
nor by the rest of the company when they were examined by a committee of parliament,
who made their report on the 5th of December.
On the 17th of the same month (after much debate and contradiction in the parliament,
many not approving the severity used against him), they came to the following resolution:

[quote]
____
That James Nayler be set in the stocks, with his head in the stocks,
in the Palace-yard, Westminster, during the space of two hours, on Thursday next,
and then be whipped by the hangman as he is conveyed through the streets of London,
from Westminster to the Old Exchange.
There he is likewise to be set in the stocks,
with his head in the stocks for the space of two hours,
between the hours of eleven and one, on Saturday next,
in each place wearing a paper containing an inscription of his crimes.
Then, at the Old Exchange his tongue is to be bored through with a hot iron,
and his forehead is to be stigmatized with the
letter B. Afterwards he is to be sent to Bristol,
and be conveyed into and through the said city on horseback, with his face backward,
and there also be publicly whipped the next market-day.
From there he is to be committed to prison in Bridewell, London,
and kept from the society of all people,
and put to hard labor till he shall be released by parliament;
during which time he is to be debarred the use of pen, ink, and paper,
and shall have no relief but what he earns by his daily labor.
____

It was long before parliament could agree upon this sentence;
for though blasphemy was supposed to be committed,
yet Nayler`'s tongue seemed not properly guilty of it,
since it was never shown that any blasphemous words had been spoken by him.^
footnote:[If we suppose it was the honor of the
Christian religion +++[+++which the parliament had in view+++]+++,
and the abhorrence of blasphemy which it felt,
why then did it not pursue the companions of Nayler with equal severity,
from whose mouths proceeded the expressions which were termed blasphemous;
and whose hearts, hands, and knees,
had been the means of erecting him into an object of worship?
For my part, I have long suspected the selection of the victim to have
arisen from a desire to crush the rising Society of Friends,
in the person of a fallen brother.
Nayler had been truly eminent and esteemed.
The others owed their notoriety only to the injurious part
which they were acting towards him.--Joseph Gurney Bevan]
Many indeed thought it a very severe judgment to be executed upon one
whose crime seemed more to proceed from a clouded understanding,
than from any willful intention of evil.
And though several persons of different religious persuasions,
being moved with compassion towards Nayler (as a
man carried away by foolish imaginations),
offered petitions to the parliament on his behalf,
yet it was resolved not to read them until the sentence was pronounced against him.

After judgment was concluded by parliament,
James Nayler was brought up to the bar; and when the speaker, sir Thomas Widdrington,
was about to pronounce the aforementioned sentence,
Nayler insisted that he did not know his offense.
To this the speaker replied, "`You shall know your offense by your punishment.`"
Nayler then bore the reading of his sentence with patience,
and afterwards appeared desirous to speak something, but liberty was denied him.
Nevertheless he was heard to say, with a composed mind,
"`I pray God will not lay it to your charge.`"

On the 18th of December, James Nayler suffered the first part of the sentence.
After having stood a full two hours with his head in the stocks, he was stripped,
tied to a cart, and whipped from the Palace-yard to the Old Exchange,
receiving three-hundred and ten stripes.
The executioner would have given him one more (as he confessed to the sheriff),
there being three-hundred and eleven kennels, but his foot slipping,
the stroke fell upon his own hand, which caused him much pain.
All this Nayler bore with so much patience and
quietness that it astonished many of the beholders,
though his body was in a most pitiful condition.
He was also much hurt with horses treading upon his feet,
whereon the print of the nails could be seen.
Rebecca Travers, a sober and honest woman (not one of his followers),
who washed his wounds,
in a certificate which was presented to the parliament and afterwards printed, says:

[quote]
____
"`There was not the space of a man`'s fingernail free from stripes and blood,
from his shoulders near to his waist.
His right arm was sorely striped, his hands much hurt by the cords,
so that they bled and swelled;
and the blood and wounds on his back did very little appear at first sight,
by reason of the abundance of dirt that covered them, till it was washed off.`"
____

His punishment was so severe,
that some judged his sentence would have been
more mild if it had been immediate execution.
Indeed it seemed that there was a party who,
not being able to prevail in parliament so as to have him sentenced to death,
yet strove to the utmost of their power to make
him sink under the weight of his punishment.
The 20th of December was the time appointed for
executing the second part of the sentence,
that is, the boring through his tongue and the stigmatizing of his forehead;
but by reason of the most cruel whipping,
he was brought to such a low state that many persons of note, moved with compassion,
presented petitions to the parliament on his behalf,
who postponed further punishment for one week.

During this seven-day interval,
several persons presented another petition to parliament, in which are these words:

[quote]
____
Your moderation and clemency in postponing the punishment of James Nayler,
in consideration of his illness of body,
has refreshed the hearts of many thousands in these cities,
who are altogether uninvolved in his practice;
wherefore we most humbly beg your pardon that we are constrained to
appear before you again (not daring to do otherwise),
requesting now that you would revoke the remaining part
of your sentence against the said James Nayler,
leaving him to the Lord, and to such gospel remedies as the Lord has sanctified.
We are persuaded you will find such a course of love
and forbearance more effectual to reclaim him;
and this will leave a seal of your love and tenderness upon our spirits.
____

This petition,
being presented at the bar of the house by about
one hundred persons on the behalf of the whole,
was accordingly read and debated by them;
but seeing that it was not likely to produce the desired effect,
the petitioners thought themselves bound in duty
and conscience to address the Lord Protector^
footnote:[Oliver Cromwell]
for the revoking of the remaining part of the sentence.
The Protector, thereupon, sent a letter to the parliament,
which occasioned some debate in the house.
And as the day for executing the remaining part of the sentence drew near,
the petitioners made yet a second address to Cromwell.
Indeed it was very remarkable that so many inhabitants of
London who were not of the society of those called Quakers,
showed themselves so much concerned in this business.
To me this seems to have proceeded from compassion towards the person of James Nayler;
whom they regarded as one who had fallen into error more through unwatchfulness,
than to have been guilty of willful blasphemy.
However, notwithstanding all these humble petitions,
it seems that the public preachers prevailed so much with Cromwell
that he could not resolve to put a stop to the intended execution.

Five of these ministers, whose names were Caryl, Manton, Nye, Griffith,
and Reynolds, came on the 24th of December,
by order from the parliament (as it was said,) to speak with
Nayler concerning the things for which he was detained,
and would not permit either a friend or any other to be present in the room with them.
A certain impartial or neutral person requested this earnestly, but was denied.
However, this same person,
coming into the prison after Nayler`'s conference with these ministers,
asked him what had taken place.
Nayler told him,
that he saw the priests had an intent to make him suffer as an evil-doer,
and had therefore denied any to be present who might
serve as an unbiased judge between them and him.
Nayler therefore told them he would not say anything,
unless what passed between them was written down, and a copy was given him to keep,
or left with the jailer, signed by them.
This was at first consented to, and the ministers propounded several questions to him,
and took his answers in writing.
They first asked him if he was sorry for the blasphemies of which he was guilty,
and whether he did recant and renounce the same.
To this his answer was, "`What blasphemies, name them?`"
But they not being able to instance any particular, he continued,
"`Would you have me recant and renounce, you know not what?`"
Then they asked him whether he did believe there was a Jesus Christ,
to which he answered, he did believe there was,
and that Jesus had taken up His dwelling in his heart and spirit,
and for the testimony of Him he now suffered.
Then one of the preachers said,
"`But I believe in a Jesus that never was in any man`'s heart;`" to which Nayler replied,
he knew no such Christ, for the Christ he knew filled heaven and earth,
and dwelt in the hearts of believers.
Next they demanded of him why he allowed those women to worship and adore him?
To which he replied, "`Bowing to the creature I deny;
but if they beheld the power of Christ, wherever it is, and bowed to it,
he had nothing by which he might oppose it.`"^
footnote:[The most that I find in his examination, either in Bristol or London,
before the committee of parliament, as published from their report,
was that Nayler acknowledged Christ in him, but never that he was Christ;
and that he took the honor given him by these people, not as to himself,
but as to Christ in him; which yet is more than any man ought to receive.
For when the beloved disciple, John, fell at the angel`'s feet to worship him, he,
(though an angel,) said unto him, '`See you do it not, I am your fellow-servant,
and of your brethren that have the testimony of Jesus, worship God.`' Rev. 19:10.
And if an angel ought not,
surely no mortal man ought to receive or accept it.
But that J. Nayler received it to himself, as a creature, he utterly denied,
stating that there could not be a more abominable thing than to take from the Creator,
and give to the creature, etc.--John Whiting]
He then said to the ministers, "`Have you thus long professed the Scriptures,
and do you now stumble at what they hold forth?`"
Whereupon they desired him to show one instance in
Scripture wherein such a practice was held forth.
He answered,
"`What do you think of the Shunammite`'s falling
down at the feet of Elisha and bowing before him?
As also several others in Scripture spoken of, as Abigail to David,
and Nebuchadnezzar to Daniel.`"
Upon hearing this, they paused awhile, and said at length,
"`That was but a civil act or acknowledgement.`"
To this Nayler replied, "`So also you might interpret the act of those women,
if your eye was not evil, seeing that the outward action is one and the same.`"
And perceiving that they were seeking to twist words from him to their own purpose,
he said, "`How soon have you forgot the works of the former bishops,
for you are now found in the same business, seeking to ensnare the innocent.`"
Whereupon the ministers rose up, and with bitterness of spirit,
burned what they had written, and left him with some harsh expressions.
And when they were departing,
he requested that the parliament send him such
questions in writing as they desired to have answered,
and give him freedom to return his reply in writing also.

By this account, it seems that Nayler, though still under a cloud,
was yet a little more clear in his understanding than before.
Nevertheless, being pursued by fierce enemies,
the execution of his sentence was not stopped, but performed on the 27th of December.
Robert Rich, a brash and disorderly man, and one of Nayler`'s followers,
was this day at the parliament door, from eight in the morning till about eleven,
crying out to the parliament men as they passed by.
To one whom he judged to be innocent in this affair, he said, "`He that dwells in love,
dwells in God, for God is love;`" and to another, whom he believed to be swayed by envy,
he said, "`He that hates his brother is a man-slayer,
and he that hates his brother is a murderer.`"
Some then supposed that Nayler would not have to suffer any further punishment,
seeing how many honorable persons had approached
the parliament and the Protector on his behalf.
But Rich, knowing how the case stood,
told the people that the "`innocent was about to suffer,`" and then cried out to
some of the parliament men that he was clear from the blood of all men,
and desired them to be as well.
He then went towards the Exchange, got onto the stocks,
and held Nayler by the hand while he was burnt in the forehead,
and bored through the tongue with a hot iron.
And being more than a little affected with Nayler`'s suffering, Rich licked his wounds,
seeking thereby (it seems) to alleviate the pain;
and then led him by the hand from the stocks.

A few particulars respecting the execution of
this part of the sentence are noteworthy.
Both the boring iron and the branding mark were red hot.
The former was held for a short time in the tongue,
that the bystanders might clearly witness the execution,
and the letter B was held to the forehead until smoke arose.
During all this time Nayler did not flinch, but when he was unbound,
he embraced the executioner.
It was also very remarkable that,
notwithstanding there must have been many thousands of people present,
yet they were very quiet, and few were heard to revile him,
or seen to throw anything at him.
And when he was burning, the people both in front and behind him, and on both sides,
with one consent removed their hats,
as seeming generally moved with compassion and goodwill towards him.

About three weeks after his suffering the second part of the sentence at London,
the third part (namely, his exposure in the stocks,
and the second whipping) was inflicted at Bristol.
According to an eye-witness, he was there bound to the back of a horse cart,
and whipped from the middle of Thomas street, over the bridge, up High street,
to the middle of Broad street, all of which he bore with wonderful patience.^
footnote:[While Nayler was dragging after a cart horse, and followed by the scourge,
Robert Rich rode before him bare-headed, and sung, '`Holy, Holy.`'
Rich, however,
does not seem to have been eminent enough among the Quakers for parliamentary censure,
and remained without punishment.--Joseph Gurney Bevan.]
I am also informed, by a letter of one Richard Snead,
an ancient man of about eighty years,
that Nayler had written a letter to the magistrates of Bristol,
wherein he had disapproved, and penitently condemned his previous behavior there.

Many now rejoiced, hoping to see the downfall of the Quakers,
and expecting that Friends were now divided amongst themselves.
But whatever disharmony existed among a few, it quickly came to an end,
for the Quakers openly spoke against Nayler and his doings,
and though they sought to restore him, they never sought to defend him.^
footnote:[Robert Barclay, in his piece called,
_William Mitchell Unmasked,_ has the following expressions concerning James Nayler.
(See p. 84) "`The story of James Nayler, which Mitchell subjoins,
any may observe to be merely brought in to render us odious,
though indeed it tends no way to our disadvantage, Nayler being in that thing,
and at that time, altogether denied by us;
and has since in print freely acknowledged his fall in that hour of temptation;
of whose sincere repentance and true return to the fellowship
of the truth we have had many evident tokens.`"
And in p. 876, _Apology Vindicated,_ in answer to an examination by John Brown,
he writes: "`But the poor man thinks (it is likely) he has hit the nail on the head,
when he says, p. 54, upon this subject, '`One thing I would ask,
what he thinks of that honor and worship that was given to James Nayler,
as he rode into Bristol, Oct. 24, 1656?'
I answer, I think it was both wicked and abominable, and so do the people called Quakers;
who thereupon disavowed him,
along with all those that had a hand in it.`"--Joseph Gurney Bevan.]

After this he was brought back to Bridewell, London, (as sentenced),
where he continued a prisoner about two years.
During this confinement he came to a true and full repentance of his transgression;
and having at some point been granted the use of pen and ink,
wrote several books and papers condemning his error, which were published in print.
On the 8th of September, 1659, he was liberated by parliament,
and went directly to Bristol, the chief scene of his offense.
There, in a public meeting,
he made an open confession of his fault in so affecting a manner,
as to draw tears from most of those who were present,
and to occasion his reconciliation with many who had been estranged from him.^
footnote:[After he was set at liberty, he went to Bristol, where in a public meeting,
he made confession of his offense, as to his former fall,
and declared in so powerful a manner, as tendered and broke the meeting into tears,
so that there were few dry eyes,
(as related by some then present,) and many were bowed
in their minds and reconciled to him.--John Whiting]
There is no doubt that he had made good use of
the solitude which his confinement afforded,
and the alteration effected in his conduct towards his friends, the Quakers,
quickly produced a return of their friendship and fellowship.

After his release, he published several more statements of recantation.
One of which is as follows:

[.embedded-content-document.paper]
--

Glory to God Almighty, who rules in the heavens,
and in whose hands are all the kingdoms of the earth; who raises up,
and casts down at His will; who has ways to confound the exaltation of men,
to chastise His children, and to make men know they are as grass before Him.
Indeed, His judgments are above the highest of men, His pity reaches the deepest misery,
and the arm of His mercy is underneath, to lift up the prisoner out of the pit,
and to save those who trust in Him from the great destruction which vain man,
through his folly, brings upon himself.
For He has delivered my soul from darkness,
and made way for my freedom out of the prison-house,
and ransomed me from the great captivity; He who divides the sea before Him,
and removes the mountains out of His way,
in the day when He takes upon Himself to deliver the oppressed
out of the hand of him that is too mighty for him in the earth.
Let His name be exalted forever, and let all flesh fear before Him,
whose breath is life to His own, but a consuming fire to the adversary.

And as for the Lord Jesus Christ, His everlasting dominion is upon earth,
and His kingdom is above all the power of darkness;
even that Christ of whom the Scriptures declare, who was, and is, and is to come,
the light of the world to all generations.
Of His coming I testify with the rest of the children of light,
who are begotten of the immortal seed; for His truth and virtue now shine in the world,
being the Savior of all who believe therein unto righteousness and eternal life.
He has been the rock of my salvation,
and His Spirit has given quietness and patience to my
soul in deep affliction for His name`'s sake.
May He be praised forever.

But condemned forever be all false worship with which any
have idolized my person in the night of my temptation,
when the power of darkness had risen above in me.
All the casting of their clothes in the way, their bowing and singing,
and all the rest of those wild actions which did in any way tend to dishonor the Lord,
or draw the minds of any from the measure of Christ Jesus in themselves,
to look at flesh (which is as grass),
or to ascribe to something visible that which belongs to Christ Jesus.
All of that I condemn,
by which the pure name of the Lord has been in any way
blasphemed through me in the time of my temptation,
or by which the spirits of any have been grieved who
truly love the Lord Jesus throughout the whole world,
in whatsoever profession.
This offense I confess, which has been sorrow of heart,
that the enemy of man`'s peace in Christ should
get this advantage in the night of my trial,
to stir up wrath and offenses in the creation of God--a
thing the simplicity of my heart did not intend,
the Lord knows; who in His endless love has given me power over it now, to condemn it.

And also that letter which was sent to me in Exeter, by John Stranger,
when I was in prison, with these words, "`Your name shall be no more James Nayler,
but Jesus;`" this I judge to be written from the imagination;
and a fear struck me when I first saw it, so I put it close into my pocket,
not intending that any should see it.
But they finding it on me, spread it abroad,
which the simplicity of my heart never approved.
So this I deny also, that the name of Christ Jesus was received instead of James Nayler,
or ascribed to me; for that name is to the promised Seed to all generations;
and he that has the Son, has the name, which is His life and power,
the salvation and the unction, into which name all the children of light are baptized.
So the name of Christ I confess before men,
which name to me has been a strong tower in the night and in the day.
This is the name of Christ Jesus, which I confess, the Son and the Lamb,
the promised Seed, wherever He speaks in male and female.
But whoever does not have the Son in himself, does not have the life,
neither can they have it by idolizing my person, or the person of any flesh.

And all those ranting, wild spirits,
who then gathered around me in that time of darkness,
and all their wild actions and wicked words against the honor of God,
and His pure Spirit and people--I deny that bad spirit,
together with its power and works.
And as far as I gave advantage, through lack of judgment,
for that evil spirit to arise in any, I justly take shame to myself,
having formerly had power over that spirit in judgment and discerning, wherever it was.
This darkness came over me through lack of watchfulness
and obedience to the pure eye of God,
and through not diligently minding the reproof of life,
which condemns the adulterous spirit.
So the adversary got advantage, who always seeks to devour;
and being taken captive from the true light,
I was walking in the night where none can work, as a wandering bird fit for a prey.
And truly, if the Lord of all my mercies had not rescued me, I would have perished;
for I was as one appointed to death and destruction,
and there was none that could deliver me.
All of this I confess, that God may be justified in His judgment,
and magnified in His endless mercies, who did not forsake His captive in the night,
even when His Spirit was daily provoked and grieved;
but has brought me forth to give glory to His name forever.

It is in my heart to confess to God, and before men,
my folly and offense in that day.
Yet there were also many things formed against me in that day (to take away
my life and bring scandal upon the Truth) of which I am not guilty at all;
such as the accusation that I committed adultery with
some of those women who came with us from Exeter prison,
and also those who were with me at Bristol the night before I suffered there.
With regard to both of these accusations I am clear before God,
who kept me in that day both in thought and deed, as to all women, like a child;
God is my witness.
This I mention in particular (hearing of some who still do not
cease to reproach God`'s Truth and people therewith) that the
mouth of enmity might be shut from evil speaking;
though this touches not my conscience.

And concerning the report that I raised Dorcas Erbury from the dead physically,
this I also deny, and I condemn this testimony to be out of the Truth;
though that power which quickens the dead I do not deny,
which is the Word of eternal life.
This I give forth,
that it may go as far as the offense against the Spirit of Truth has gone abroad,
that all burdens may be taken off of the Truth, and that the Truth, the true light,
and all that walk therein may be cleared, and the deeds of darkness be condemned;
and also that all who are yet in darkness may not act in the night,
but stay their minds upon God, who dwells in the light,
and has no fellowship with the workers of iniquity.
For had I done this when darkness first came upon me, and not been led by others,
I would not have run myself against the Rock to
be broken (which Rock had so long borne me,
and of whom I had so largely drank, and of which I now drink in measure).
To Him be the glory of all, and to Him every tongue must confess, as Judge and Savior,
God over all, blessed forever.

--

[.offset]
Nayler added to this an exhortation to the reader how to behave if, at any time,
he comes to be tempted to sin, and also a warning not to rely too much upon gifts,
wisdom, and knowledge, and then concluded with these words:

[.embedded-content-document]
--

These things I have learned in the depths and in secret, when I was alone,
and now declare openly in the day of Your mercy, O Lord.
Glory to the Highest forevermore,
who has thus far set me free to praise His righteousness and His mercy;
and to the eternal, invisible, pure God, over all, be fear, obedience,
and glory forevermore. Amen.

[.signed-section-signature]
James Nayler

--

[.offset]
He wrote another paper wherein he related at large,
how it was by unwatchfulness that he came to fall,
after having once obtained much victory over the power of Satan, by the grace of God,
when he daily walked humbly in his fear;
for he had formerly labored faithfully in the ministry of the gospel for some years.
But what is remarkable is that,
though he used to pass with great boldness through all opposition,
yet coming to the city of London (just prior to his fall) he entered
it with the greatest fear that ever he knew in any place,
foreseeing in spirit (as he relates) something to befall him there,
but not knowing what it might be:

[.embedded-content-document.paper]
--

Yet I had at that time (he continues) the same
presence and power I had known before,
in whatever place or service I was led of the Spirit;
for keeping in that life I never returned without victory in the Lord Jesus Christ.
But not minding in all things to stand single
and low to the motions of that endless life,
by Him to be led in all things within and without,
but giving way to the reasoning part with respect to
some things which in themselves had no seeming evil,
little by little my mind was drawn out after trifles, vanities, and persons,
which took hold in the affectionate part.
By this my mind was drawn out from the constant watch and pure fear,
into which I was once begotten.
Thus, having in a great measure lost my own guide, and darkness having come upon me,
I sought a place where I might be alone to weep and cry before the Lord,
that I might find His face and recover my condition.

But by then my adversary, who had long waited his opportunity, had got in,
and bestirred himself every way, so that I could not be hidden;
and several messages came to me, some true, and some false, as I have seen since.
So, knowing some to be true (namely, how I had lost my condition),
with this I let in the false messages also;
and so letting go of what little remained of the true light in myself,
I gave myself up wholly to be led by others,
whose work was then to divide me from the children of light,^
footnote:[i.e. The Society of Friends]
which was done, though much was done by several of them to prevent it,
and in tender love many labored to help me.
And after I was led out from them,
the Lord God of my life sent several of His servants with His word after me,
calling for my return, all of which was rejected.
Yes, my provocation in that time of temptation was
exceedingly great against the pure love of God;
yet He left me not.
And after I had given myself under the power of my adversary,
and darkness had risen above in me,
then he so prevailed that all things were turned and perverted against my right seeing,
hearing, or understanding; only I had a secret hope and faith in my God,
whom I had formerly served, that He would bring me through it, and to the end of it,
and that I should again see the day of my redemption from under it all.
And this quieted my soul in my greatest tribulation.

--

[.offset]
The author then,
seriously exhorting others who might also fall into great temptation,
concludes with these words:

[.embedded-content-document]
--

He who has saved my soul from death thus far,
and has lifted my feet up out of the pit, even to Him be glory forever.
Let every troubled soul trust in Him, for His mercy endures forever.

[.signed-section-signature]
James Nayler

--

[.offset]
That he came to a perfect recovery out from having been so deceived,
seems to appear plainly by the following thanksgiving to God for His mercies,
which he also published after his fall:

[.embedded-content-document]
--

It is in my heart to praise You, O my God.
Let me never forget You, what You have been to me in the night,
by Your presence in the day of trial, when I was beset in darkness,
when I was cast out as a wandering bird, when I was assaulted with strong temptations;
then Your presence in secret did preserve me, and in a low state I felt You near me.
When the floods sought to sweep me away,
You set a boundary for them how far they should pass over.
When my way was through the sea, and when I passed under the mountains,
there You were present with me.
When the weight of the hills was upon me, You upheld me,
else I would have sunk under the earth.
When I was as one altogether helpless;
when tribulation and anguish was upon me day and night,
and the earth was without foundation; when I went on in the way of wrath,
and passed by the gates of hell; when all comforts stood afar off,
and he that is my enemy had dominion; when I was cast into the pit,
and was as one appointed to death; when I was between the millstones,
and as one crushed with the weight of his adversary; as a father, You were with me, yes,
the rock of Your presence.
When the mouths of lions roared against me, and fear took hold of my soul in the pit,
then I called upon You in the night, and my cries were strong before You daily.
You answered me from Your habitation, and delivered me from Your dwelling-place; saying,
"`I will set you above all your fears,
and lift up your feet above the head of oppression.`"
I believed, and was strengthened, and Your word was my salvation.

You did fight on my behalf when I wrestled with death;
and when darkness would have shut me up, then Your light shone about me,
and Your banner was over my head.
When my work was in the furnace, and as I passed through the fire,
I was not consumed by You, though the flames ascended above my head.
When I beheld the dreadful visions and was amongst the fiery spirits,
Your faith stayed me, else through fear I had fallen.
I saw You and believed, so the enemy could not prevail.

When I look back into Your works I am astonished, and see no end of Your praises.
Glory, glory to You, says my soul, and let my heart be ever filled with thanksgiving.
While Your works remain, they shall show forth Your power.
Then did You lay the foundation of the earth, and lead me under the waters,
and in the deep did You show me wonders, and Your forming of the world.
By Your hand You led me in safety, till You showed me the pillars of the earth.
Then did the heavens shower down, they were covered with darkness,
and the powers thereof were shaken, and Your glory descended.
Yes, You filled the lower parts of the earth with gladness,
and the springs of the valleys were opened, and Your showers descended abundantly,
so that the earth was filled with virtue.
You made Your plant to spring, and the thirsty soul became as a watered garden.
Then did You lift me out of the pit, and set me forth in the sight of my enemies.
You proclaimed liberty to the captive, and called my acquaintances near me.
They to whom I had been a wonder, looked upon me,
and in Your love I obtained favor from those who had forsaken me.
Then did gladness swallow up sorrow, and I forsook all my troubles; and I said,
"`How good is it that man be proved in the night, that he may know his folly;
so that every mouth may become silent in Your hand until You make man known to himself,
and have slain the boaster, and showed him the vanity that vexes Your spirit.`"

[.signed-section-signature]
James Nayler

--

This plainly appears to be a poetical piece,
as the author makes use of allegorical sayings throughout to
signify the great anguish and tribulation he had been under,
expressing how the powers of darkness had so
prevailed in him as to grieve the Spirit of God,
to put a stumbling block in the way of the simple,
and to cause the way of Truth to be evilly spoken of.
For, by the wiles of Satan,
he had accepted the idolatrous honor of those whom he should have swiftly reproved;
and so stupefied was he in his understanding,
that he imagined that the bowing and kneeling
before him was not done on account of his person,
but for Christ.
With this false opinion he blinded himself for a time, till it pleased God to pity him,
and to give him light again,
after he had suffered such an unheard of punishment for his transgression,
as has already been related.
And because his preaching against unrighteousness in former
times had fallen so sharply on all classes of people,
undisguisedly and clearly demonstrating the Christian duty of rulers, preachers,
and lawyers, so the hatred of his enemies was the fiercer.
Indeed, several had long been angry with him,
and took occasion from his crime to revenge themselves barbarously upon him,
making him suffer a cruel punishment which was
in no way proportionable to his transgression.

But while he lay in the house of correction,
he wrote several papers to manifest his regret and repentance for his crime;
some of which have already been inserted,
but the following letter has since come to my hand.
It is a letter to his friends, written with his own hand:

[.embedded-content-document.letter]
--

[.salutation]
Dear brethren,

My heart is broken this day for the offense
that I have occasioned God`'s truth and people,
and especially you, who in dear love followed me, seeking me in faithfulness to God,
which love I rejected.
For I was bound in that from which I could not come forth, till God`'s hand brought me,
to whose love I now confess.
I beseech you to forgive wherein I evilly repaid your love in that day.
God knows my sorrow for it (since I have been enabled to see it),
that ever I should offend the Spirit of God in any, or reject His counsel.
And now that paper you have seen lies much upon me, and I greatly fear to offend further,
or to do something amiss whereby the innocent Truth or the people of God should suffer,
or that I should disobey therein.

Unless the Lord Himself keeps you from me,
I beseech you let nothing else hinder your coming to me,
that I might have your help in the Lord.
In the mercies of Christ Jesus I beg this of you, as if it were your own case;
let me not be forgotten by you.

And I entreat you, speak to Henry Clarke, or whoever else I have most offended;
and by the power of God, and in the Spirit of Christ Jesus,
I am willing to confess my offense, that God`'s love may arise in all hearts as before,
if it be His will, who alone can remove what stands in the way.
I do not intend to cover anything; God is my witness herein.

--

[.offset]
He also wrote several other confessions of his faults about this time, in one of which,
amongst others, I find these words:

[.embedded-content-document]
--

And concerning you, the tender plants of my Father,
who have suffered because of me, or with me,
in what the Lord has allowed to be done with me,
in this time of great trial and temptation: May the Almighty God of love,
who has numbered every sigh, and put every tear in His bottle,
reward it a thousand fold into your bosoms, in the day of your need,
when you shall come to be tried and tempted.
And in the meantime, may He fulfill our joy with His love, which you seek after.
The Lord knows, it was never in my heart to cause you to mourn,
whose suffering is my greatest sorrow that ever yet came upon me,
for you are innocent herein.

--

[.offset]
When he had finished this letter, and set his name,
he then wrote the following postscript:

[.embedded-content-document]
--

I beseech you (all that can),
to receive this even as you would desire to be received of the Lord; and as for the rest,
may the Lord give me patience to suffer till He makes up the breach.

--

[.offset]
While he was in Bridewell, he wrote to the parliament,
who had punished him as a blasphemer,
to let them know his true opinion concerning Jesus Christ.

[.embedded-content-document]
--

Christ Jesus (the Immanuel, of whose sufferings the Scriptures declare),
Him alone I confess before men.
For His sake I have denied whatever was dear to me in this world, that I might win Him,
and be found in Him, and not in myself.
I seek to serve Him alone, in spirit, soul and body, night and day,
according to the measure of grace working in me, that in me He may be glorified,
whether by life or death.

But to ascribe this name, power, and virtue, to James Nayler,
or to that which had a beginning, and must return to dust, or for that to be exalted,
or worshipped, to me is great idolatry,
and with the Spirit of Christ Jesus in me it is condemned;
which Spirit leads to lowliness, meekness, and long-suffering.

So having an opportunity given, I am willing with readiness,
in the fear of God the Father, in honor to Christ Jesus,
and in order to take off all offenses from every simple heart,
to declare this to all the world, without guile or deceit,
daily finding it to be my work to seek peace in truth with all men in that Spirit.

[.signed-section-signature]
James Nayler

--

After this,
hearing that some had wronged him concerning something
he had spoken to the committee of the parliament,
and understanding how men had perverted his words, he wrote a paper,
declaring himself further concerning his belief of Christ, and His sufferings, and death, etc.
He also denounced a paper which someone had published anonymously,
under the title of _James Nayler`'s Recantation,_
wherein they had much perverted his words.

[.embedded-content-document.paper]
--

And with regard +++[+++he writes]
to the printing of that paper called _James Nayler`'s Recantation,_ it was not done by me,
nor with my knowledge in the least, nor do I yet at all know the man that has done it.
But I know it was done out of the Truth, and against the Truth,
and for evil towards me, whoever it was.
May the Lord God of my life, who has kept me alive in all distress, turn it for good,
and forgive the evil.
Nevertheless, what measure of truth there is in the paper, I shall acknowledge:
for thus it was, that after I was put into the hole at Bridewell,
I heard of many wild actions done by a sort of people who pretended to take my side.
These were busily stirred up in that day, and with much violence,
and many unseemly actions,
went into the meetings of the people of the Lord called Quakers,
on purpose to hinder their peaceable meetings.
And yet these would take the holy and pure name
of God and Christ frequently in their mouths,
whereby the name of the Lord was much dishonored, and His pure Spirit grieved,
for they caused much disorder in many places of
the nation to the dishonor of Christ Jesus,
for which I felt wrath from God.
But when I understood that they had any influence through me,
I used all means I could to declare against that evil spirit,
which under the name of God and Christ, was against God and Christ,
and against His Truth and people.
I wrote something about a year and a half ago in denial of these spirits,
which it seems to me the author of this paper has seen,
and to it has added the thoughts of his own heart,
and so has published his work of darkness, and people know not what to make of it.

Therefore, so far as this paper testifies against those unclean, ranting spirits,
and all the actions wherein the holy name of God has been dishonored,
and His Spirit grieved, that far I acknowledge it.
But in that it suggests that I denied the Lord Jesus Christ,
and His Truth which has called me out of the world,
or His people whom He has called into light--in these things I deny it.
For in the patience and tribulation of Christ Jesus,
and with those who have the power this day to testify
therein against all the evils of this present world,
I am one in heart and soul to the utmost of my strength,
till the coming of the Lord Jesus over all.
May the throne of meekness and truth be set on the top of all enmity and deceit.
And now, in the faith and power of Christ, I am given up to live or die,
to suffer or rejoice, as God wills, even so be it, without murmuring.

[.signed-section-signature]
James Nayler

--

This is certain,
that James Nayler came to very great sorrow and deep humiliation of mind; and therefore,
because God forgives the transgressions of the penitent, and blots them out,
and remembers them no more,
so James Nayler`'s friends could do no other than forgive his crime,
and thus take back the lost sheep into their society.
And having afterwards obtained his liberty,
he behaved himself as became a Christian--honest and blameless in conduct,
and patiently bearing the reproach of his former offenses.

When King Charles the Second had ascended the throne,
a man by the name of Richard Blome published a book entitled, _The Fanatic History,_
which was said to be published with the approbation of orthodox theologians (so called),
and dedicated by him to the king.
This book struck chiefly against the Quakers,
and was stuffed with a multitude of lying stories,
along with a greatly exaggerated account of the fall of James Nayler.
He being then alive,
took up the pen and answered the falsities contained in it that were related to himself.
And because Richard Blome, in his dedication to the king, said,
"`That if his majesty does not put forth his
royal hand of power quickly to restrain them,
they are so numerous and seducing that they will, in a little time,
diffuse their poison over the better part of his kingdom,
which none but a royal authority can stifle,`"
so Nayler responded in the following words:

[.embedded-content-document]
--

What has happened to your spiritual weapons?
Have not your teachers told people of the strength of Truth, and the power of godliness?
Have you lost both, and do you now run to the arm of flesh,
to get errors (as you call them) stifled, or else your hope is lost,
and your faith fails you?
Did ever any of Christ`'s ministers take off their
spiritual weapons and run to the arm of flesh,
or to a carnal weapon to stop seducers?
I say, no.
This they never did;
but with spiritual weapons they wrestled and overcame spiritual wickedness,
and with spiritual weapons they cut down heresies, blasphemies, and false worship,
cleared the churches of Christ of them, and brought them down before them in the world;
for indeed, none could resist the Spirit by which they spoke.
But the false priests and false worshippers
cried out to rulers and people (as you do now),
'`Help us, or all will be overrun:
for they that turn the world upside down are come here!`'^
footnote:[Acts 17:6; 21:28]
And then the rude multitude ran upon them, and fell upon them with rods and fists,
and assaulted the houses that entertained them, even as you do,
and so hauled them before rulers, and put them in prison, and often whipped them.
Is this your cry for help against so contemptible a people (as you count them)?
What!
Have you preached and wrestled yourselves out of all hope and faith,
so that now you must either have sudden help from the king or all is lost and overrun?
Surely then it may be said, you have been bad watchmen, and idle shepherds.

And whereas you say your book is of great importance,
and so you presume to make King Charles the patron of it,
and then ask pardon for your presumption: I say, you indeed have need of his pardon.
For the substance of your book is made up of false accusations,
gathered up out of books formerly written against us,
all of which have been disproved by clear answers, and printed several times over.
And to these old accusations you have added a few new ones, as false as the old,
and have spied out the failings of a few,
who have mourned before God that ever they should sin
and give occasion to the enemies of God so to blaspheme.
And to all of this you have included many things which were done and spoken by others,
who are not of our society, nor ever were.

And as for the charges you have against James Nayler,
through the everlasting mercy of my God, I have yet a being amongst the living,
and breath to answer for myself,
despite the intentions of many cruel and bloodthirsty spirits,
who pursued my soul unto death (as much as in their power lay)
in that day of my calamity when my adversary had risen above,
and wherein I was made a sign to a backsliding generation.
These rejoiced against this piece of dust,
and had little pity towards him that had fallen into their hands;
at which time God was just in giving me up for my disobedience, for a moment,
as a father to correct me.
Yet these should not have sought to aggravate things against me, as you do now;
for it was a day of deep distress, and it lay sore upon my soul,
and the merciful God saw it, who, though He was displeased with me for a time,
yet His thoughts were not to cast me off forever, but to extend mercy,
as it is at this day.
Eternal glory be to His name from my delivered soul.

But, O man, or men, whoever you are,
whose work it is to gather the failings of God`'s people in the time of their temptation,
or in the night of their trial, and aggravate them,
adding thereto the wickedness and mischievous lies of your own heart,
as you have done in your book,
and then thereby to reproach God`'s everlasting holy Truth--I say,
you are put to work by an evil spirit,
and you do but show yourselves enemies to God and His children.
For it is our great sorrow,
that any of us should have given occasion for Truth to be spoken against;
and it has been trouble of soul to all the
people of God who have ever loved righteousness,
when they have thus occasioned the joy of the wicked,
or fed the man that watches for iniquity and feeds on mischief.
Yet know this, you that are of that brood, God will not cast off His people,
though He is sometimes provoked to correct them,
even before their adversaries (which is a sign to them),
yet His anger is but for a moment, and His favor shall return as streams of life.

But that which was, and is the sorrow of my heart,
is the advantage which the enemy then took against the name of Christ, His Truth,
and His despised people, in that time of my temptation,
which is what you are now pursuing with hatred and with lies,
saying that I was suspected to have a woman in bed with
me the night before I suffered at Bristol.
But as to this, and several other false things you have written in your book,
I am clear before the Lord, so that they touch me not at all.
And it is to God alone I look, in His time, to be cleared from all offenses in His sight,
who alone knows my heart in this thing, and in whose presence I can say,
that nothing is more odious and burdensome to my soul than that any
of the glory or worship which belongs to God or to Christ,
should be given to flesh and blood, either in myself or others.
And as for how it was with me in that day, there are many who talk, but few who know;
so the judgment of such I bear, desiring that none, in their judging of me,
condemn themselves in the sight of God; for His counsels are great and deep,
and the end of His work is past finding out, till He Himself reveals them.

And however myself or any others may yet be left alone to be tried in the night,
or should any of us utterly fall,
or whatever else may be acted by any man or woman that is not right in God`'s sight,
yet in vain do you gather up sin and watch for iniquity,
in order to cast it upon the light of Christ.
For it is the light of Christ that condemns sin in every enlightened mind.
And this I know by the Spirit of Jesus, which I have received, and which works in me,
that this work of yours is not His work, nor is it His seed.
You are not in Him that loves His enemies,
but the old accuser of the brethren is he that works strongly in you.
And in that light which you reproach, you are seen to be the man that makes lies,
and "`carries tales to shed blood.`" Ezek. 22:9.

--

This and much more did James Nayler write to
answer the falsehoods of which he was accused,
and to show that the fault of his crime must in no way
be attributed to the doctrine which he had professed,
as many envious persons in those times asserted; namely,
that his fall was a consequence of the doctrine that
men must take heed to the saving grace of God,
the inward anointing,
or the light wherewith every man coming into the world is enlightened from God.

After his fall and recovery, James Nayler wrote many papers and edifying letters,
and ever after manifested himself to be a man of great self-denial,
being very careful of his steppings.
George Whitehead, who lodged with him at a house in London in 1659 and 1660,
bears this testimony of him, "`that he was revived by the Lord`'s power,
and in measure restored to his ancient testimony,
which he bore publicly in various parts of the nation as the Lord enabled him,
both in his ministry and writings.
And,`" adds Whitehead,
"`he walked in much brotherly love and simplicity among us, until his end came.`"

At last, departing from the city of London,
about the latter end of the Eighth month 1660, he headed North,
intending to go home to his wife and children at Wakefield, in Yorkshire.
On the way he was seen by a Friend of Hertford,
sitting by the road in a very serious and weighty frame of mind,
who invited him to his house, but Nayler refused,
signifying that it was his mind to press forward.
He went on foot as far as Huntingdonshire where he was observed by
another Friend passing through the town in such a heavenly frame,
that he looked as if he had been redeemed from the earth, and was a stranger on it,
seeking a better country and inheritance.
But going some miles beyond Huntingdon, he was taken ill, having been, as it was said,
robbed along the way and left bound.
Whether he received any personal injury is not certainly known,
but being found in a field by a countryman toward evening,
he was taken or went to a Friend`'s house at Holm, not far from King`'s Rippon,
where Thomas Parnel, a doctor of medicine, came to visit him.
Being asked if any friends at London should be sent for to come and see him;
he said "`No,`" but expressed his care and love to them.
Being shifted on the bed he said, "`You have refreshed my body,
may the Lord refresh your souls.`"
About two hours before his death,
he spoke the following words in the presence of several witnesses:

[.embedded-content-document.letter]
--

There is a spirit which I feel, that delights to do no evil,
nor to revenge any wrong, but delights to endure all things,
in hope to enjoy its own in the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptations.
As it bears no evil in itself, so it conceives none in thought to any other.
If it is betrayed, it bears it;
for its ground and spring is the mercies and forgiveness of God.
Its crown is meekness, its life is everlasting love unfeigned.
It takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it or acknowledge its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor does it murmur at grief and oppression.
It never rejoices but through sufferings, for with the world`'s joy it is murdered.
I found it alone, being forsaken.
I have fellowship therein with those who lived
in dens and in desolate places of the earth,
who through death obtained this resurrection, and eternal holy life.

--

[.asterism]
'''

Thus he departed this life, in peace with the Lord, about the Ninth month, 1660,
in the 44th year of his age,
and was buried in Thomas Parnel`'s burying ground at King`'s Rippon.

[.offset]
In conclusion, I borrow the words of Joseph Wyeth,
from whose writings the following is taken:

[.embedded-content-document]
--

James Nayler was a man who had been highly favored of
God with a good degree of grace,
which was sufficient for him, had he kept to its teachings; for while he did so,
he was exemplary in godliness and great humility, was powerful in word and doctrine,
and thereby instrumental in the hand of God for turning many from darkness to light,
and from the power of Satan to the power of God.
But he, poor man, became exalted above measure, through the abundance of revelation,
and in that exaltation did depart from the grace and Holy Spirit of God,
which had been his sufficient teacher.
Then blindness came over him, and he allowed himself to be accounted above what he ought.
Here he slipped and fell, but not irrecoverably; for it did please God,
in His infinite mercy, in the day of his affliction,
to give him a sight and sense of his outgoings and fall, and also a place for repentance.
And with the prodigal, James Nayler humbled himself for his transgression,
and besought God with true contrition of soul to
pardon his offenses through Jesus Christ.
God, I firmly believe, forgave him, for He pardons the truly penitent.
Then did his people receive him with great joy,
for he who had gone astray from God was now returned to the Father`'s house,
and he who had separated himself from them through his iniquity, was now,
through repentance and forsaking it, returned into the unity of the faith,
and their holy fellowship in the gospel of Christ.
And I do hereby testify,
that I esteem it a particular mark of God`'s acknowledging His people,
in bringing back into unity with them a man who had so dangerously fallen,
as did James Nayler.
And here let none revile, but take heed lest they also,
in the hour of their temptation, do fall away.
Nor let any boastingly say, "`Where is your God?`"
or blasphemously suppose that His grace is not sufficient for man in
temptation because the tempted may go from and neglect the teaching of it.
For we see with David and Peter that,
as their transgression came by their departing from this infallible guide,
the Holy Spirit, so their recovery was only by it.

--
